// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbActivity : DbIconDefinition = {
    iconName: "activity",
    svgPathData: {duotone: ["M15 4.25c.3 0 .571.179.69.455l2.804 6.545H22a.75.75 0 0 1 0 1.5h-4a.75.75 0 0 1-.69-.455L15 6.904 9.69 19.295a.75.75 0 0 1-1.38 0L5.506 12.75H2a.75.75 0 0 1 0-1.5h4c.3 0 .571.179.69.455L9 17.096l5.31-12.391A.75.75 0 0 1 15 4.25Z"],fill: ["M15 4.25c.3 0 .571.179.69.455l2.804 6.545H22a.75.75 0 0 1 0 1.5h-4a.75.75 0 0 1-.69-.455L15 6.904 9.69 19.295a.75.75 0 0 1-1.38 0L5.506 12.75H2a.75.75 0 0 1 0-1.5h4c.3 0 .571.179.69.455L9 17.096l5.31-12.391A.75.75 0 0 1 15 4.25Z"],line: ["M15 4.25c.3 0 .571.179.69.455l2.804 6.545H22a.75.75 0 0 1 0 1.5h-4a.75.75 0 0 1-.69-.455L15 6.904 9.69 19.295a.75.75 0 0 1-1.38 0L5.506 12.75H2a.75.75 0 0 1 0-1.5h4c.3 0 .571.179.69.455L9 17.096l5.31-12.391A.75.75 0 0 1 15 4.25Z"],}
}

export default dbActivity;
