// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerRightSmall : DbIconDefinition = {
    iconName: "arrowsCornerRightSmall",
    svgPathData: {duotone: ["M13 7.75a.75.75 0 0 1 0-1.5h4a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8.81l-7.44 7.44H11a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v2.19l7.44-7.44Z"],fill: ["M13 7.75a.75.75 0 0 1 0-1.5h4a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8.81l-7.44 7.44H11a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v2.19l7.44-7.44Z"],line: ["M13 7.75a.75.75 0 0 1 0-1.5h4a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8.81l-7.44 7.44H11a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v2.19l7.44-7.44Z"],}
}

export default dbArrowsCornerRightSmall;
