// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineDownSmall : DbIconDefinition = {
    iconName: "arrowLineDownSmall",
    svgPathData: {duotone: ["M12.75 7v5.19l2.22-2.22a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3.5 3.5a.75.75 0 0 1-1.06 0l-3.5-3.5a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l2.22 2.22V7a.75.75 0 0 1 1.5 0ZM7 17.75a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],fill: ["M12.75 7v5.19l2.22-2.22a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3.5 3.5a.75.75 0 0 1-1.06 0l-3.5-3.5a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l2.22 2.22V7a.75.75 0 0 1 1.5 0ZM7 17.75a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],line: ["M12.75 7v5.19l2.22-2.22a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3.5 3.5a.75.75 0 0 1-1.06 0l-3.5-3.5a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l2.22 2.22V7a.75.75 0 0 1 1.5 0ZM7 17.75a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowLineDownSmall;
