// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowUp : DbIconDefinition = {
    iconName: "arrowUp",
    svgPathData: {duotone: ["M11.47 4.47a.75.75 0 0 1 1.06 0l6 6a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4.72-4.72V19a.75.75 0 0 1-1.5 0V6.81l-4.72 4.72a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Z"],fill: ["M11.47 4.47a.75.75 0 0 1 1.06 0l6 6a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4.72-4.72V19a.75.75 0 0 1-1.5 0V6.81l-4.72 4.72a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Z"],line: ["M11.47 4.47a.75.75 0 0 1 1.06 0l6 6a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4.72-4.72V19a.75.75 0 0 1-1.5 0V6.81l-4.72 4.72a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Z"],}
}

export default dbArrowUp;
