// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowCircleClockwiseSmall : DbIconDefinition = {
    iconName: "arrowCircleClockwiseSmall",
    svgPathData: {duotone: ["M17 12a5 5 0 1 1-10 0 5 5 0 1 1 10 0Z","m12.53 4.47 2 2a.75.75 0 0 1 0 1.06l-2 2a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l.72-.72H12A4.25 4.25 0 1 0 16.25 12a.75.75 0 0 1 1.5 0 5.75 5.75 0 1 1-11.5 0A5.75 5.75 0 0 1 12 6.25h.19l-.72-.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215Z"],fill: ["m12.53 4.47 2 2a.75.75 0 0 1 0 1.06l-2 2a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l.72-.72H12A4.25 4.25 0 1 0 16.25 12a.75.75 0 0 1 1.5 0 5.75 5.75 0 1 1-11.5 0A5.75 5.75 0 0 1 12 6.25h.19l-.72-.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215Z"],line: ["m12.53 4.47 2 2a.75.75 0 0 1 0 1.06l-2 2a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l.72-.72H12A4.25 4.25 0 1 0 16.25 12a.75.75 0 0 1 1.5 0 5.75 5.75 0 1 1-11.5 0A5.75 5.75 0 0 1 12 6.25h.19l-.72-.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215Z"],}
}

export default dbArrowCircleClockwiseSmall;
