// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnRightDown : DbIconDefinition = {
    iconName: "arrowReturnRightDown",
    svgPathData: {duotone: ["M5.75 9v4a.75.75 0 0 1-1.5 0V9a6.75 6.75 0 1 1 13.5 0v10.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l2.72 2.72V9a5.25 5.25 0 0 0-10.5 0Z"],fill: ["M5.75 9v4a.75.75 0 0 1-1.5 0V9a6.75 6.75 0 1 1 13.5 0v10.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l2.72 2.72V9a5.25 5.25 0 0 0-10.5 0Z"],line: ["M5.75 9v4a.75.75 0 0 1-1.5 0V9a6.75 6.75 0 1 1 13.5 0v10.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l2.72 2.72V9a5.25 5.25 0 0 0-10.5 0Z"],}
}

export default dbArrowReturnRightDown;
