// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineUpLeftSmall : DbIconDefinition = {
    iconName: "arrowLineUpLeftSmall",
    svgPathData: {duotone: ["m11.81 7.8 3.67 3.67a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-3.67-3.669V12a.75.75 0 0 1-1.5 0V7.05A.75.75 0 0 1 10 6.3h4.95a.75.75 0 0 1 0 1.5ZM17 17.75H7a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],fill: ["m11.81 7.8 3.67 3.67a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-3.67-3.669V12a.75.75 0 0 1-1.5 0V7.05A.75.75 0 0 1 10 6.3h4.95a.75.75 0 0 1 0 1.5ZM17 17.75H7a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],line: ["m11.81 7.8 3.67 3.67a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-3.67-3.669V12a.75.75 0 0 1-1.5 0V7.05A.75.75 0 0 1 10 6.3h4.95a.75.75 0 0 1 0 1.5ZM17 17.75H7a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowLineUpLeftSmall;
