// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowUpRightSmall : DbIconDefinition = {
    iconName: "arrowUpRightSmall",
    svgPathData: {duotone: ["M15.535 14.871a.75.75 0 0 1-.75-.75v-3.846l-5.79 5.79a.75.75 0 0 1-1.061-1.06l5.79-5.79H9.88a.75.75 0 0 1 0-1.5h5.656a.75.75 0 0 1 .75.75v5.656a.75.75 0 0 1-.75.75Z"],fill: ["M15.535 14.871a.75.75 0 0 1-.75-.75v-3.846l-5.79 5.79a.75.75 0 0 1-1.061-1.06l5.79-5.79H9.88a.75.75 0 0 1 0-1.5h5.656a.75.75 0 0 1 .75.75v5.656a.75.75 0 0 1-.75.75Z"],line: ["M15.535 14.871a.75.75 0 0 1-.75-.75v-3.846l-5.79 5.79a.75.75 0 0 1-1.061-1.06l5.79-5.79H9.88a.75.75 0 0 1 0-1.5h5.656a.75.75 0 0 1 .75.75v5.656a.75.75 0 0 1-.75.75Z"],}
}

export default dbArrowUpRightSmall;
