// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowCircleCounterClockwiseSmall : DbIconDefinition = {
    iconName: "arrowCircleCounterClockwiseSmall",
    svgPathData: {duotone: ["M17 12a5 5 0 1 1-10 0 5 5 0 1 1 10 0Z","M11.47 4.47a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-.72.72H12a5.75 5.75 0 1 1 0 11.5A5.75 5.75 0 0 1 6.25 12a.75.75 0 0 1 1.5 0A4.25 4.25 0 1 0 12 7.75h-.19l.72.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2-2a.75.75 0 0 1 0-1.06Z"],fill: ["M11.47 4.47a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-.72.72H12a5.75 5.75 0 1 1 0 11.5A5.75 5.75 0 0 1 6.25 12a.75.75 0 0 1 1.5 0A4.25 4.25 0 1 0 12 7.75h-.19l.72.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2-2a.75.75 0 0 1 0-1.06Z"],line: ["M11.47 4.47a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-.72.72H12a5.75 5.75 0 1 1 0 11.5A5.75 5.75 0 0 1 6.25 12a.75.75 0 0 1 1.5 0A4.25 4.25 0 1 0 12 7.75h-.19l.72.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2-2a.75.75 0 0 1 0-1.06Z"],}
}

export default dbArrowCircleCounterClockwiseSmall;
