// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowRightSmall : DbIconDefinition = {
    iconName: "arrowRightSmall",
    svgPathData: {duotone: ["M12.47 7.47a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H7a.75.75 0 0 1 0-1.5h8.19l-2.72-2.72a.75.75 0 0 1 0-1.06Z"],fill: ["M12.47 7.47a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H7a.75.75 0 0 1 0-1.5h8.19l-2.72-2.72a.75.75 0 0 1 0-1.06Z"],line: ["M12.47 7.47a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H7a.75.75 0 0 1 0-1.5h8.19l-2.72-2.72a.75.75 0 0 1 0-1.06Z"],}
}

export default dbArrowRightSmall;
