// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineDownRight : DbIconDefinition = {
    iconName: "arrowLineDownRight",
    svgPathData: {duotone: ["M6.873 9.51a.748.748 0 0 1 .332-1.265.75.75 0 0 1 .729.205l7.912 7.912v-3.847a.75.75 0 0 1 1.5 0v5.657a.75.75 0 0 1-.75.75H10.94a.75.75 0 0 1 0-1.5h3.847ZM20 2.825H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],fill: ["M6.873 9.51a.748.748 0 0 1 .332-1.265.75.75 0 0 1 .729.205l7.912 7.912v-3.847a.75.75 0 0 1 1.5 0v5.657a.75.75 0 0 1-.75.75H10.94a.75.75 0 0 1 0-1.5h3.847ZM20 2.825H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],line: ["M6.873 9.51a.748.748 0 0 1 .332-1.265.75.75 0 0 1 .729.205l7.912 7.912v-3.847a.75.75 0 0 1 1.5 0v5.657a.75.75 0 0 1-.75.75H10.94a.75.75 0 0 1 0-1.5h3.847ZM20 2.825H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowLineDownRight;
