// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnLeftUpSmall : DbIconDefinition = {
    iconName: "arrowReturnLeftUpSmall",
    svgPathData: {duotone: ["M16.25 13.5V11a.75.75 0 0 1 1.5 0v2.5a4.25 4.25 0 0 1-8.5 0V8.81l-1.72 1.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l3-3a.75.75 0 0 1 1.06 0l3 3a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-1.72-1.72v4.69a2.75 2.75 0 1 0 5.5 0Z"],fill: ["M16.25 13.5V11a.75.75 0 0 1 1.5 0v2.5a4.25 4.25 0 0 1-8.5 0V8.81l-1.72 1.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l3-3a.75.75 0 0 1 1.06 0l3 3a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-1.72-1.72v4.69a2.75 2.75 0 1 0 5.5 0Z"],line: ["M16.25 13.5V11a.75.75 0 0 1 1.5 0v2.5a4.25 4.25 0 0 1-8.5 0V8.81l-1.72 1.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l3-3a.75.75 0 0 1 1.06 0l3 3a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-1.72-1.72v4.69a2.75 2.75 0 1 0 5.5 0Z"],}
}

export default dbArrowReturnLeftUpSmall;
