// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineLeft : DbIconDefinition = {
    iconName: "arrowLineLeft",
    svgPathData: {duotone: ["M21 11.25a.75.75 0 0 1 0 1.5H9.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.72 2.72ZM3.75 20a.75.75 0 0 1-1.5 0V4a.75.75 0 0 1 1.5 0Z"],fill: ["M21 11.25a.75.75 0 0 1 0 1.5H9.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.72 2.72ZM3.75 20a.75.75 0 0 1-1.5 0V4a.75.75 0 0 1 1.5 0Z"],line: ["M21 11.25a.75.75 0 0 1 0 1.5H9.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.72 2.72ZM3.75 20a.75.75 0 0 1-1.5 0V4a.75.75 0 0 1 1.5 0Z"],}
}

export default dbArrowLineLeft;
