// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnDownLeftSmall : DbIconDefinition = {
    iconName: "arrowReturnDownLeftSmall",
    svgPathData: {duotone: ["M13.5 7.75H11a.75.75 0 0 1 0-1.5h2.5a4.25 4.25 0 0 1 0 8.5H8.81l1.72 1.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-3-3a.75.75 0 0 1 0-1.06l3-3a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-1.72 1.72h4.69a2.75 2.75 0 1 0 0-5.5Z"],fill: ["M13.5 7.75H11a.75.75 0 0 1 0-1.5h2.5a4.25 4.25 0 0 1 0 8.5H8.81l1.72 1.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-3-3a.75.75 0 0 1 0-1.06l3-3a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-1.72 1.72h4.69a2.75 2.75 0 1 0 0-5.5Z"],line: ["M13.5 7.75H11a.75.75 0 0 1 0-1.5h2.5a4.25 4.25 0 0 1 0 8.5H8.81l1.72 1.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-3-3a.75.75 0 0 1 0-1.06l3-3a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-1.72 1.72h4.69a2.75 2.75 0 1 0 0-5.5Z"],}
}

export default dbArrowReturnDownLeftSmall;
