// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnUpLeft : DbIconDefinition = {
    iconName: "arrowReturnUpLeft",
    svgPathData: {duotone: ["M15 18.25a5.25 5.25 0 0 0 0-10.5H4.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042L4.81 6.25H15a6.75 6.75 0 1 1 0 13.5h-4a.75.75 0 0 1 0-1.5Z"],fill: ["M15 18.25a5.25 5.25 0 0 0 0-10.5H4.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042L4.81 6.25H15a6.75 6.75 0 1 1 0 13.5h-4a.75.75 0 0 1 0-1.5Z"],line: ["M15 18.25a5.25 5.25 0 0 0 0-10.5H4.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042L4.81 6.25H15a6.75 6.75 0 1 1 0 13.5h-4a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowReturnUpLeft;
