// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowCircleCounterClockwise : DbIconDefinition = {
    iconName: "arrowCircleCounterClockwise",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M20.25 12A8.25 8.25 0 0 0 5.254 7.25H8.5a.75.75 0 0 1 0 1.5h-5A.75.75 0 0 1 2.75 8V3a.75.75 0 0 1 1.5 0v3.083A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12a.75.75 0 0 1 1.5 0 8.25 8.25 0 0 0 16.5 0Z"],fill: ["M20.25 12A8.25 8.25 0 0 0 5.254 7.25H8.5a.75.75 0 0 1 0 1.5h-5A.75.75 0 0 1 2.75 8V3a.75.75 0 0 1 1.5 0v3.083A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12a.75.75 0 0 1 1.5 0 8.25 8.25 0 0 0 16.5 0Z"],line: ["M20.25 12A8.25 8.25 0 0 0 5.254 7.25H8.5a.75.75 0 0 1 0 1.5h-5A.75.75 0 0 1 2.75 8V3a.75.75 0 0 1 1.5 0v3.083A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12a.75.75 0 0 1 1.5 0 8.25 8.25 0 0 0 16.5 0Z"],}
}

export default dbArrowCircleCounterClockwise;
