// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineDown : DbIconDefinition = {
    iconName: "arrowLineDown",
    svgPathData: {duotone: ["M12.75 3v11.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l2.72 2.72V3a.75.75 0 0 1 1.5 0ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],fill: ["M12.75 3v11.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l2.72 2.72V3a.75.75 0 0 1 1.5 0ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],line: ["M12.75 3v11.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l2.72 2.72V3a.75.75 0 0 1 1.5 0ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowLineDown;
