// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineDownLeftSmall : DbIconDefinition = {
    iconName: "arrowLineDownLeftSmall",
    svgPathData: {duotone: ["M11.811 16.25h3.139a.75.75 0 0 1 0 1.5H10a.75.75 0 0 1-.75-.75v-4.95a.75.75 0 0 1 1.5 0v3.14l3.67-3.67a.75.75 0 0 1 1.061 1.06Zm5.177-10a.75.75 0 0 1 0 1.5h-10a.75.75 0 0 1 0-1.5Z"],fill: ["M11.811 16.25h3.139a.75.75 0 0 1 0 1.5H10a.75.75 0 0 1-.75-.75v-4.95a.75.75 0 0 1 1.5 0v3.14l3.67-3.67a.75.75 0 0 1 1.061 1.06Zm5.177-10a.75.75 0 0 1 0 1.5h-10a.75.75 0 0 1 0-1.5Z"],line: ["M11.811 16.25h3.139a.75.75 0 0 1 0 1.5H10a.75.75 0 0 1-.75-.75v-4.95a.75.75 0 0 1 1.5 0v3.14l3.67-3.67a.75.75 0 0 1 1.061 1.06Zm5.177-10a.75.75 0 0 1 0 1.5h-10a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowLineDownLeftSmall;
