// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineLeftSmall : DbIconDefinition = {
    iconName: "arrowLineLeftSmall",
    svgPathData: {duotone: ["M17 11.25a.75.75 0 0 1 0 1.5h-5.19l2.22 2.22a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-3.5-3.5a.75.75 0 0 1 0-1.06l3.5-3.5a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.22 2.22ZM6.25 17V7a.75.75 0 0 1 1.5 0v10a.75.75 0 0 1-1.5 0Z"],fill: ["M17 11.25a.75.75 0 0 1 0 1.5h-5.19l2.22 2.22a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-3.5-3.5a.75.75 0 0 1 0-1.06l3.5-3.5a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.22 2.22ZM6.25 17V7a.75.75 0 0 1 1.5 0v10a.75.75 0 0 1-1.5 0Z"],line: ["M17 11.25a.75.75 0 0 1 0 1.5h-5.19l2.22 2.22a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-3.5-3.5a.75.75 0 0 1 0-1.06l3.5-3.5a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.22 2.22ZM6.25 17V7a.75.75 0 0 1 1.5 0v10a.75.75 0 0 1-1.5 0Z"],}
}

export default dbArrowLineLeftSmall;
