// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineDownRightSmall : DbIconDefinition = {
    iconName: "arrowLineDownRightSmall",
    svgPathData: {duotone: ["M8.52 12.58a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l3.67 3.67v-3.14a.75.75 0 0 1 1.5 0V17a.75.75 0 0 1-.75.75H9.05a.75.75 0 0 1 0-1.5h3.14ZM7 6.25h10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1 0-1.5Z"],fill: ["M8.52 12.58a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l3.67 3.67v-3.14a.75.75 0 0 1 1.5 0V17a.75.75 0 0 1-.75.75H9.05a.75.75 0 0 1 0-1.5h3.14ZM7 6.25h10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1 0-1.5Z"],line: ["M8.52 12.58a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l3.67 3.67v-3.14a.75.75 0 0 1 1.5 0V17a.75.75 0 0 1-.75.75H9.05a.75.75 0 0 1 0-1.5h3.14ZM7 6.25h10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowLineDownRightSmall;
