// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowDown : DbIconDefinition = {
    iconName: "arrowDown",
    svgPathData: {duotone: ["m11.47 19.53-6-6a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l4.72 4.72V5a.75.75 0 0 1 1.5 0v12.19l4.72-4.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-6 6a.75.75 0 0 1-1.06 0Z"],fill: ["m11.47 19.53-6-6a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l4.72 4.72V5a.75.75 0 0 1 1.5 0v12.19l4.72-4.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-6 6a.75.75 0 0 1-1.06 0Z"],line: ["m11.47 19.53-6-6a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l4.72 4.72V5a.75.75 0 0 1 1.5 0v12.19l4.72-4.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-6 6a.75.75 0 0 1-1.06 0Z"],}
}

export default dbArrowDown;
