// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineRight : DbIconDefinition = {
    iconName: "arrowLineRight",
    svgPathData: {duotone: ["M3 11.25h11.19l-2.72-2.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H3a.75.75 0 0 1 0-1.5ZM20.25 20V4a.75.75 0 0 1 1.5 0v16a.75.75 0 0 1-1.5 0Z"],fill: ["M3 11.25h11.19l-2.72-2.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H3a.75.75 0 0 1 0-1.5ZM20.25 20V4a.75.75 0 0 1 1.5 0v16a.75.75 0 0 1-1.5 0Z"],line: ["M3 11.25h11.19l-2.72-2.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H3a.75.75 0 0 1 0-1.5ZM20.25 20V4a.75.75 0 0 1 1.5 0v16a.75.75 0 0 1-1.5 0Z"],}
}

export default dbArrowLineRight;
