// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerLeftSplit : DbIconDefinition = {
    iconName: "arrowsCornerLeftSplit",
    svgPathData: {duotone: ["M11 4.25a.75.75 0 0 1 0 1.5H6.81l3.72 3.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L5.75 6.81V11a.75.75 0 0 1-1.5 0V5A.75.75 0 0 1 5 4.25Zm2 15.5a.75.75 0 0 1 0-1.5h4.19l-3.72-3.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3.72 3.72V13a.75.75 0 0 1 1.5 0v6a.75.75 0 0 1-.75.75Z"],fill: ["M11 4.25a.75.75 0 0 1 0 1.5H6.81l3.72 3.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L5.75 6.81V11a.75.75 0 0 1-1.5 0V5A.75.75 0 0 1 5 4.25Zm2 15.5a.75.75 0 0 1 0-1.5h4.19l-3.72-3.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3.72 3.72V13a.75.75 0 0 1 1.5 0v6a.75.75 0 0 1-.75.75Z"],line: ["M11 4.25a.75.75 0 0 1 0 1.5H6.81l3.72 3.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L5.75 6.81V11a.75.75 0 0 1-1.5 0V5A.75.75 0 0 1 5 4.25Zm2 15.5a.75.75 0 0 1 0-1.5h4.19l-3.72-3.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3.72 3.72V13a.75.75 0 0 1 1.5 0v6a.75.75 0 0 1-.75.75Z"],}
}

export default dbArrowsCornerLeftSplit;
