// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowUpLeft : DbIconDefinition = {
    iconName: "arrowUpLeft",
    svgPathData: {duotone: ["M15.5 6.75H7.81l10.72 10.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L6.75 7.81v7.69a.75.75 0 0 1-1.5 0V6A.75.75 0 0 1 6 5.25h9.5a.75.75 0 0 1 0 1.5Z"],fill: ["M15.5 6.75H7.81l10.72 10.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L6.75 7.81v7.69a.75.75 0 0 1-1.5 0V6A.75.75 0 0 1 6 5.25h9.5a.75.75 0 0 1 0 1.5Z"],line: ["M15.5 6.75H7.81l10.72 10.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L6.75 7.81v7.69a.75.75 0 0 1-1.5 0V6A.75.75 0 0 1 6 5.25h9.5a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowUpLeft;
