// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnUpRightSmall : DbIconDefinition = {
    iconName: "arrowReturnUpRightSmall",
    svgPathData: {duotone: ["M10.5 16.25H13a.75.75 0 0 1 0 1.5h-2.5a4.25 4.25 0 0 1 0-8.5h4.69l-1.72-1.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3 3a.75.75 0 0 1 0 1.06l-3 3a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l1.72-1.72H10.5a2.75 2.75 0 1 0 0 5.5Z"],fill: ["M10.5 16.25H13a.75.75 0 0 1 0 1.5h-2.5a4.25 4.25 0 0 1 0-8.5h4.69l-1.72-1.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3 3a.75.75 0 0 1 0 1.06l-3 3a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l1.72-1.72H10.5a2.75 2.75 0 1 0 0 5.5Z"],line: ["M10.5 16.25H13a.75.75 0 0 1 0 1.5h-2.5a4.25 4.25 0 0 1 0-8.5h4.69l-1.72-1.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3 3a.75.75 0 0 1 0 1.06l-3 3a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l1.72-1.72H10.5a2.75 2.75 0 1 0 0 5.5Z"],}
}

export default dbArrowReturnUpRightSmall;
