// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerLeftSmall : DbIconDefinition = {
    iconName: "arrowsCornerLeftSmall",
    svgPathData: {duotone: ["M6.25 7A.75.75 0 0 1 7 6.25h4a.75.75 0 0 1 0 1.5H8.81l7.44 7.44V13a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75h-4a.75.75 0 0 1 0-1.5h2.19L7.75 8.81V11a.75.75 0 0 1-1.5 0Z"],fill: ["M6.25 7A.75.75 0 0 1 7 6.25h4a.75.75 0 0 1 0 1.5H8.81l7.44 7.44V13a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75h-4a.75.75 0 0 1 0-1.5h2.19L7.75 8.81V11a.75.75 0 0 1-1.5 0Z"],line: ["M6.25 7A.75.75 0 0 1 7 6.25h4a.75.75 0 0 1 0 1.5H8.81l7.44 7.44V13a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75h-4a.75.75 0 0 1 0-1.5h2.19L7.75 8.81V11a.75.75 0 0 1-1.5 0Z"],}
}

export default dbArrowsCornerLeftSmall;
