// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowDownRightSmall : DbIconDefinition = {
    iconName: "arrowDownRightSmall",
    svgPathData: {duotone: ["M9.129 15.535a.75.75 0 0 1 .75-.75h3.846l-5.791-5.79a.75.75 0 1 1 1.06-1.061l5.791 5.79V9.88a.75.75 0 0 1 1.5 0v5.656a.75.75 0 0 1-.75.75H9.88a.75.75 0 0 1-.75-.75Z"],fill: ["M9.129 15.535a.75.75 0 0 1 .75-.75h3.846l-5.791-5.79a.75.75 0 1 1 1.06-1.061l5.791 5.79V9.88a.75.75 0 0 1 1.5 0v5.656a.75.75 0 0 1-.75.75H9.88a.75.75 0 0 1-.75-.75Z"],line: ["M9.129 15.535a.75.75 0 0 1 .75-.75h3.846l-5.791-5.79a.75.75 0 1 1 1.06-1.061l5.791 5.79V9.88a.75.75 0 0 1 1.5 0v5.656a.75.75 0 0 1-.75.75H9.88a.75.75 0 0 1-.75-.75Z"],}
}

export default dbArrowDownRightSmall;
