// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowUpLeftSmall : DbIconDefinition = {
    iconName: "arrowUpLeftSmall",
    svgPathData: {duotone: ["M14.871 8.464a.75.75 0 0 1-.75.75h-3.846l5.79 5.791a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-5.79-5.79v3.846a.75.75 0 0 1-1.5 0V8.464a.75.75 0 0 1 .75-.75h5.656a.75.75 0 0 1 .75.75Z"],fill: ["M14.871 8.464a.75.75 0 0 1-.75.75h-3.846l5.79 5.791a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-5.79-5.79v3.846a.75.75 0 0 1-1.5 0V8.464a.75.75 0 0 1 .75-.75h5.656a.75.75 0 0 1 .75.75Z"],line: ["M14.871 8.464a.75.75 0 0 1-.75.75h-3.846l5.79 5.791a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-5.79-5.79v3.846a.75.75 0 0 1-1.5 0V8.464a.75.75 0 0 1 .75-.75h5.656a.75.75 0 0 1 .75.75Z"],}
}

export default dbArrowUpLeftSmall;
