// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineUp : DbIconDefinition = {
    iconName: "arrowLineUp",
    svgPathData: {duotone: ["M12.75 9.81V21a.75.75 0 0 1-1.5 0V9.81l-2.72 2.72a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215ZM4 3.75a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],fill: ["M12.75 9.81V21a.75.75 0 0 1-1.5 0V9.81l-2.72 2.72a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215ZM4 3.75a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],line: ["M12.75 9.81V21a.75.75 0 0 1-1.5 0V9.81l-2.72 2.72a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215ZM4 3.75a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowLineUp;
