// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineUpRight : DbIconDefinition = {
    iconName: "arrowLineUpRight",
    svgPathData: {duotone: ["M6.873 13.566h.001l7.913-7.912H10.94a.75.75 0 0 1 0-1.5h5.656a.75.75 0 0 1 .75.75v5.657a.75.75 0 0 1-1.5 0V6.714l-7.912 7.912a.75.75 0 1 1-1.061-1.06ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],fill: ["M6.873 13.566h.001l7.913-7.912H10.94a.75.75 0 0 1 0-1.5h5.656a.75.75 0 0 1 .75.75v5.657a.75.75 0 0 1-1.5 0V6.714l-7.912 7.912a.75.75 0 1 1-1.061-1.06ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],line: ["M6.873 13.566h.001l7.913-7.912H10.94a.75.75 0 0 1 0-1.5h5.656a.75.75 0 0 1 .75.75v5.657a.75.75 0 0 1-1.5 0V6.714l-7.912 7.912a.75.75 0 1 1-1.061-1.06ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowLineUpRight;
