// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowCircleClockwise : DbIconDefinition = {
    iconName: "arrowCircleClockwise",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M3.75 12a8.25 8.25 0 0 0 16.5 0 .75.75 0 0 1 1.5 0A9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12a9.75 9.75 0 0 1 17.5-5.917V3a.75.75 0 0 1 1.5 0v5a.75.75 0 0 1-.75.75h-5a.75.75 0 0 1 0-1.5h3.246A8.25 8.25 0 0 0 3.75 12Z"],fill: ["M3.75 12a8.25 8.25 0 0 0 16.5 0 .75.75 0 0 1 1.5 0A9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12a9.75 9.75 0 0 1 17.5-5.917V3a.75.75 0 0 1 1.5 0v5a.75.75 0 0 1-.75.75h-5a.75.75 0 0 1 0-1.5h3.246A8.25 8.25 0 0 0 3.75 12Z"],line: ["M3.75 12a8.25 8.25 0 0 0 16.5 0 .75.75 0 0 1 1.5 0A9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12a9.75 9.75 0 0 1 17.5-5.917V3a.75.75 0 0 1 1.5 0v5a.75.75 0 0 1-.75.75h-5a.75.75 0 0 1 0-1.5h3.246A8.25 8.25 0 0 0 3.75 12Z"],}
}

export default dbArrowCircleClockwise;
