// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLeftSmall : DbIconDefinition = {
    iconName: "arrowLeftSmall",
    svgPathData: {duotone: ["M11.53 7.47a.75.75 0 0 1 0 1.06l-2.72 2.72H17a.75.75 0 0 1 0 1.5H8.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.75.75 0 0 1 1.06 0Z"],fill: ["M11.53 7.47a.75.75 0 0 1 0 1.06l-2.72 2.72H17a.75.75 0 0 1 0 1.5H8.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.75.75 0 0 1 1.06 0Z"],line: ["M11.53 7.47a.75.75 0 0 1 0 1.06l-2.72 2.72H17a.75.75 0 0 1 0 1.5H8.81l2.72 2.72a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-4-4a.75.75 0 0 1 0-1.06l4-4a.75.75 0 0 1 1.06 0Z"],}
}

export default dbArrowLeftSmall;
