// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnLeftUp : DbIconDefinition = {
    iconName: "arrowReturnLeftUp",
    svgPathData: {duotone: ["M18.25 15v-4a.75.75 0 0 1 1.5 0v4a6.75 6.75 0 1 1-13.5 0V4.81L3.53 7.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L7.75 4.81V15a5.25 5.25 0 0 0 10.5 0Z"],fill: ["M18.25 15v-4a.75.75 0 0 1 1.5 0v4a6.75 6.75 0 1 1-13.5 0V4.81L3.53 7.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L7.75 4.81V15a5.25 5.25 0 0 0 10.5 0Z"],line: ["M18.25 15v-4a.75.75 0 0 1 1.5 0v4a6.75 6.75 0 1 1-13.5 0V4.81L3.53 7.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L7.75 4.81V15a5.25 5.25 0 0 0 10.5 0Z"],}
}

export default dbArrowReturnLeftUp;
