// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerRightSplitSmall : DbIconDefinition = {
    iconName: "arrowsCornerRightSplitSmall",
    svgPathData: {duotone: ["M11 17.75H7a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v2.188l2.053-2.051a.75.75 0 0 1 1.061 1.06L8.81 16.25H11a.75.75 0 0 1 0 1.5Zm2-11.5h4a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8.811l-2.053 2.052a.75.75 0 0 1-1.061-1.06L15.19 7.75H13a.75.75 0 0 1 0-1.5Z"],fill: ["M11 17.75H7a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v2.188l2.053-2.051a.75.75 0 0 1 1.061 1.06L8.81 16.25H11a.75.75 0 0 1 0 1.5Zm2-11.5h4a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8.811l-2.053 2.052a.75.75 0 0 1-1.061-1.06L15.19 7.75H13a.75.75 0 0 1 0-1.5Z"],line: ["M11 17.75H7a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v2.188l2.053-2.051a.75.75 0 0 1 1.061 1.06L8.81 16.25H11a.75.75 0 0 1 0 1.5Zm2-11.5h4a.75.75 0 0 1 .75.75v4a.75.75 0 0 1-1.5 0V8.811l-2.053 2.052a.75.75 0 0 1-1.061-1.06L15.19 7.75H13a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowsCornerRightSplitSmall;
