// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineUpSmall : DbIconDefinition = {
    iconName: "arrowLineUpSmall",
    svgPathData: {duotone: ["M12.75 17a.75.75 0 0 1-1.5 0v-5.19l-2.22 2.22a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l3.5-3.5a.75.75 0 0 1 1.06 0l3.5 3.5a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.22-2.22ZM7 6.25h10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1 0-1.5Z"],fill: ["M12.75 17a.75.75 0 0 1-1.5 0v-5.19l-2.22 2.22a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l3.5-3.5a.75.75 0 0 1 1.06 0l3.5 3.5a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.22-2.22ZM7 6.25h10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1 0-1.5Z"],line: ["M12.75 17a.75.75 0 0 1-1.5 0v-5.19l-2.22 2.22a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l3.5-3.5a.75.75 0 0 1 1.06 0l3.5 3.5a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.22-2.22ZM7 6.25h10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowLineUpSmall;
