// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnUpRight : DbIconDefinition = {
    iconName: "arrowReturnUpRight",
    svgPathData: {duotone: ["M9 18.25h4a.75.75 0 0 1 0 1.5H9a6.75 6.75 0 1 1 0-13.5h10.19l-2.72-2.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H9a5.25 5.25 0 0 0 0 10.5Z"],fill: ["M9 18.25h4a.75.75 0 0 1 0 1.5H9a6.75 6.75 0 1 1 0-13.5h10.19l-2.72-2.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H9a5.25 5.25 0 0 0 0 10.5Z"],line: ["M9 18.25h4a.75.75 0 0 1 0 1.5H9a6.75 6.75 0 1 1 0-13.5h10.19l-2.72-2.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.72-2.72H9a5.25 5.25 0 0 0 0 10.5Z"],}
}

export default dbArrowReturnUpRight;
