// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerLeft : DbIconDefinition = {
    iconName: "arrowsCornerLeft",
    svgPathData: {duotone: ["M11 5.75H6.81l11.44 11.44V13a.75.75 0 0 1 1.5 0v6a.75.75 0 0 1-.75.75h-6a.75.75 0 0 1 0-1.5h4.19L5.75 6.81V11a.75.75 0 0 1-1.5 0V5A.75.75 0 0 1 5 4.25h6a.75.75 0 0 1 0 1.5Z"],fill: ["M11 5.75H6.81l11.44 11.44V13a.75.75 0 0 1 1.5 0v6a.75.75 0 0 1-.75.75h-6a.75.75 0 0 1 0-1.5h4.19L5.75 6.81V11a.75.75 0 0 1-1.5 0V5A.75.75 0 0 1 5 4.25h6a.75.75 0 0 1 0 1.5Z"],line: ["M11 5.75H6.81l11.44 11.44V13a.75.75 0 0 1 1.5 0v6a.75.75 0 0 1-.75.75h-6a.75.75 0 0 1 0-1.5h4.19L5.75 6.81V11a.75.75 0 0 1-1.5 0V5A.75.75 0 0 1 5 4.25h6a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowsCornerLeft;
