// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowUpRight : DbIconDefinition = {
    iconName: "arrowUpRight",
    svgPathData: {duotone: ["M8.5 6.75a.75.75 0 0 1 0-1.5H18a.75.75 0 0 1 .75.75v9.5a.75.75 0 0 1-1.5 0V7.81L6.53 18.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042L16.19 6.75Z"],fill: ["M8.5 6.75a.75.75 0 0 1 0-1.5H18a.75.75 0 0 1 .75.75v9.5a.75.75 0 0 1-1.5 0V7.81L6.53 18.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042L16.19 6.75Z"],line: ["M8.5 6.75a.75.75 0 0 1 0-1.5H18a.75.75 0 0 1 .75.75v9.5a.75.75 0 0 1-1.5 0V7.81L6.53 18.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042L16.19 6.75Z"],}
}

export default dbArrowUpRight;
