// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCircleCounterClockwiseSmall : DbIconDefinition = {
    iconName: "arrowsCircleCounterClockwiseSmall",
    svgPathData: {duotone: ["M17 12a5 5 0 1 1-10 0 5 5 0 1 1 10 0Z","M14 14.75a.75.75 0 0 1 0-1.5h3a.75.75 0 0 1 .75.75v3a.75.75 0 0 1-1.5 0v-.943a5.877 5.877 0 0 1-10.012-2.91.751.751 0 0 1 1.471-.294 4.377 4.377 0 0 0 7.693 1.897H14Zm-5.403-5.5H10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75V7a.75.75 0 0 1 1.5 0v.942a5.877 5.877 0 0 1 10.011 2.911.751.751 0 0 1-1.471.294A4.377 4.377 0 0 0 8.597 9.25Z"],fill: ["M14 14.75a.75.75 0 0 1 0-1.5h3a.75.75 0 0 1 .75.75v3a.75.75 0 0 1-1.5 0v-.943a5.877 5.877 0 0 1-10.012-2.91.751.751 0 0 1 1.471-.294 4.377 4.377 0 0 0 7.693 1.897H14Zm-5.403-5.5H10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75V7a.75.75 0 0 1 1.5 0v.942a5.877 5.877 0 0 1 10.011 2.911.751.751 0 0 1-1.471.294A4.377 4.377 0 0 0 8.597 9.25Z"],line: ["M14 14.75a.75.75 0 0 1 0-1.5h3a.75.75 0 0 1 .75.75v3a.75.75 0 0 1-1.5 0v-.943a5.877 5.877 0 0 1-10.012-2.91.751.751 0 0 1 1.471-.294 4.377 4.377 0 0 0 7.693 1.897H14Zm-5.403-5.5H10a.75.75 0 0 1 0 1.5H7a.75.75 0 0 1-.75-.75V7a.75.75 0 0 1 1.5 0v.942a5.877 5.877 0 0 1 10.011 2.911.751.751 0 0 1-1.471.294A4.377 4.377 0 0 0 8.597 9.25Z"],}
}

export default dbArrowsCircleCounterClockwiseSmall;
