// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineDownLeft : DbIconDefinition = {
    iconName: "arrowLineDownLeft",
    svgPathData: {duotone: ["m17.127 9.51-.001-.002-7.912 7.912h3.847a.75.75 0 0 1 0 1.5H7.404a.75.75 0 0 1-.75-.75v-5.657a.75.75 0 0 1 1.5 0v3.847l7.912-7.91a.75.75 0 0 1 1.061 1.06ZM20 2.825H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],fill: ["m17.127 9.51-.001-.002-7.912 7.912h3.847a.75.75 0 0 1 0 1.5H7.404a.75.75 0 0 1-.75-.75v-5.657a.75.75 0 0 1 1.5 0v3.847l7.912-7.91a.75.75 0 0 1 1.061 1.06ZM20 2.825H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],line: ["m17.127 9.51-.001-.002-7.912 7.912h3.847a.75.75 0 0 1 0 1.5H7.404a.75.75 0 0 1-.75-.75v-5.657a.75.75 0 0 1 1.5 0v3.847l7.912-7.91a.75.75 0 0 1 1.061 1.06ZM20 2.825H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowLineDownLeft;
