// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerLeftSplitSmall : DbIconDefinition = {
    iconName: "arrowsCornerLeftSplitSmall",
    svgPathData: {duotone: ["M11 6.25a.75.75 0 0 1 0 1.5H8.81l2.054 2.053a.75.75 0 0 1-1.061 1.06L7.75 8.812V11a.75.75 0 0 1-1.5 0V7A.75.75 0 0 1 7 6.25Zm2 11.5a.75.75 0 0 1 0-1.5h2.19l-2.054-2.053a.75.75 0 0 1 1.061-1.06l2.053 2.052V13a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75Z"],fill: ["M11 6.25a.75.75 0 0 1 0 1.5H8.81l2.054 2.053a.75.75 0 0 1-1.061 1.06L7.75 8.812V11a.75.75 0 0 1-1.5 0V7A.75.75 0 0 1 7 6.25Zm2 11.5a.75.75 0 0 1 0-1.5h2.19l-2.054-2.053a.75.75 0 0 1 1.061-1.06l2.053 2.052V13a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75Z"],line: ["M11 6.25a.75.75 0 0 1 0 1.5H8.81l2.054 2.053a.75.75 0 0 1-1.061 1.06L7.75 8.812V11a.75.75 0 0 1-1.5 0V7A.75.75 0 0 1 7 6.25Zm2 11.5a.75.75 0 0 1 0-1.5h2.19l-2.054-2.053a.75.75 0 0 1 1.061-1.06l2.053 2.052V13a.75.75 0 0 1 1.5 0v4a.75.75 0 0 1-.75.75Z"],}
}

export default dbArrowsCornerLeftSplitSmall;
