// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowDownLeftSmall : DbIconDefinition = {
    iconName: "arrowDownLeftSmall",
    svgPathData: {duotone: ["M8.465 9.129a.75.75 0 0 1 .75.75v3.846l5.79-5.791a.75.75 0 1 1 1.061 1.06l-5.79 5.791h3.846a.75.75 0 0 1 0 1.5H8.465a.75.75 0 0 1-.75-.75V9.88a.75.75 0 0 1 .75-.75Z"],fill: ["M8.465 9.129a.75.75 0 0 1 .75.75v3.846l5.79-5.791a.75.75 0 1 1 1.061 1.06l-5.79 5.791h3.846a.75.75 0 0 1 0 1.5H8.465a.75.75 0 0 1-.75-.75V9.88a.75.75 0 0 1 .75-.75Z"],line: ["M8.465 9.129a.75.75 0 0 1 .75.75v3.846l5.79-5.791a.75.75 0 1 1 1.061 1.06l-5.79 5.791h3.846a.75.75 0 0 1 0 1.5H8.465a.75.75 0 0 1-.75-.75V9.88a.75.75 0 0 1 .75-.75Z"],}
}

export default dbArrowDownLeftSmall;
