// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowTrendDownSmall : DbIconDefinition = {
    iconName: "arrowTrendDownSmall",
    svgPathData: {duotone: ["M6.49 8.45a.75.75 0 0 1 1.06.04l2.223 2.4a.765.765 0 0 0 1.121 0 2.264 2.264 0 0 1 3.323 0l2.033 2.196V11.4a.75.75 0 0 1 1.5 0V15a.75.75 0 0 1-.75.75h-3.333a.75.75 0 0 1 0-1.5h1.616l-2.167-2.34a.765.765 0 0 0-1.121 0 2.264 2.264 0 0 1-3.323 0L6.45 9.51a.75.75 0 0 1 .04-1.06Z"],fill: ["M6.49 8.45a.75.75 0 0 1 1.06.04l2.223 2.4a.765.765 0 0 0 1.121 0 2.264 2.264 0 0 1 3.323 0l2.033 2.196V11.4a.75.75 0 0 1 1.5 0V15a.75.75 0 0 1-.75.75h-3.333a.75.75 0 0 1 0-1.5h1.616l-2.167-2.34a.765.765 0 0 0-1.121 0 2.264 2.264 0 0 1-3.323 0L6.45 9.51a.75.75 0 0 1 .04-1.06Z"],line: ["M6.49 8.45a.75.75 0 0 1 1.06.04l2.223 2.4a.765.765 0 0 0 1.121 0 2.264 2.264 0 0 1 3.323 0l2.033 2.196V11.4a.75.75 0 0 1 1.5 0V15a.75.75 0 0 1-.75.75h-3.333a.75.75 0 0 1 0-1.5h1.616l-2.167-2.34a.765.765 0 0 0-1.121 0 2.264 2.264 0 0 1-3.323 0L6.45 9.51a.75.75 0 0 1 .04-1.06Z"],}
}

export default dbArrowTrendDownSmall;
