// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineUpLeft : DbIconDefinition = {
    iconName: "arrowLineUpLeft",
    svgPathData: {duotone: ["M17.127 13.566a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018L8.153 6.715v3.847a.75.75 0 0 1-1.5 0V4.904a.75.75 0 0 1 .75-.75h5.657a.75.75 0 0 1 0 1.5H9.215ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],fill: ["M17.127 13.566a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018L8.153 6.715v3.847a.75.75 0 0 1-1.5 0V4.904a.75.75 0 0 1 .75-.75h5.657a.75.75 0 0 1 0 1.5H9.215ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],line: ["M17.127 13.566a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018L8.153 6.715v3.847a.75.75 0 0 1-1.5 0V4.904a.75.75 0 0 1 .75-.75h5.657a.75.75 0 0 1 0 1.5H9.215ZM4 20.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowLineUpLeft;
