// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowRight : DbIconDefinition = {
    iconName: "arrowRight",
    svgPathData: {duotone: ["M12.47 18.53a.75.75 0 0 1 0-1.06l4.72-4.72H5a.75.75 0 0 1 0-1.5h12.19l-4.72-4.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l6 6a.75.75 0 0 1 0 1.06l-6 6a.75.75 0 0 1-1.06 0Z"],fill: ["M12.47 18.53a.75.75 0 0 1 0-1.06l4.72-4.72H5a.75.75 0 0 1 0-1.5h12.19l-4.72-4.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l6 6a.75.75 0 0 1 0 1.06l-6 6a.75.75 0 0 1-1.06 0Z"],line: ["M12.47 18.53a.75.75 0 0 1 0-1.06l4.72-4.72H5a.75.75 0 0 1 0-1.5h12.19l-4.72-4.72a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l6 6a.75.75 0 0 1 0 1.06l-6 6a.75.75 0 0 1-1.06 0Z"],}
}

export default dbArrowRight;
