// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnDownLeft : DbIconDefinition = {
    iconName: "arrowReturnDownLeft",
    svgPathData: {duotone: ["M15 5.75h-4a.75.75 0 0 1 0-1.5h4a6.75 6.75 0 1 1 0 13.5H4.81l2.72 2.72a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-4-4a.75.75 0 0 1 0-1.06l4-4a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.72 2.72H15a5.25 5.25 0 0 0 0-10.5Z"],fill: ["M15 5.75h-4a.75.75 0 0 1 0-1.5h4a6.75 6.75 0 1 1 0 13.5H4.81l2.72 2.72a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-4-4a.75.75 0 0 1 0-1.06l4-4a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.72 2.72H15a5.25 5.25 0 0 0 0-10.5Z"],line: ["M15 5.75h-4a.75.75 0 0 1 0-1.5h4a6.75 6.75 0 1 1 0 13.5H4.81l2.72 2.72a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-4-4a.75.75 0 0 1 0-1.06l4-4a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-2.72 2.72H15a5.25 5.25 0 0 0 0-10.5Z"],}
}

export default dbArrowReturnDownLeft;
