// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnRightDownSmall : DbIconDefinition = {
    iconName: "arrowReturnRightDownSmall",
    svgPathData: {duotone: ["M7.75 10.5V13a.75.75 0 0 1-1.5 0v-2.5a4.25 4.25 0 0 1 8.5 0v4.69l1.72-1.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3 3a.75.75 0 0 1-1.06 0l-3-3a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l1.72 1.72V10.5a2.75 2.75 0 1 0-5.5 0Z"],fill: ["M7.75 10.5V13a.75.75 0 0 1-1.5 0v-2.5a4.25 4.25 0 0 1 8.5 0v4.69l1.72-1.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3 3a.75.75 0 0 1-1.06 0l-3-3a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l1.72 1.72V10.5a2.75 2.75 0 1 0-5.5 0Z"],line: ["M7.75 10.5V13a.75.75 0 0 1-1.5 0v-2.5a4.25 4.25 0 0 1 8.5 0v4.69l1.72-1.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3 3a.75.75 0 0 1-1.06 0l-3-3a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l1.72 1.72V10.5a2.75 2.75 0 1 0-5.5 0Z"],}
}

export default dbArrowReturnRightDownSmall;
