// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowDownRight : DbIconDefinition = {
    iconName: "arrowDownRight",
    svgPathData: {duotone: ["M8.5 17.25h7.69L5.47 6.53a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l10.72 10.72V8.5a.75.75 0 0 1 1.5 0V18a.75.75 0 0 1-.75.75H8.5a.75.75 0 0 1 0-1.5Z"],fill: ["M8.5 17.25h7.69L5.47 6.53a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l10.72 10.72V8.5a.75.75 0 0 1 1.5 0V18a.75.75 0 0 1-.75.75H8.5a.75.75 0 0 1 0-1.5Z"],line: ["M8.5 17.25h7.69L5.47 6.53a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l10.72 10.72V8.5a.75.75 0 0 1 1.5 0V18a.75.75 0 0 1-.75.75H8.5a.75.75 0 0 1 0-1.5Z"],}
}

export default dbArrowDownRight;
