// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineUpRightSmall : DbIconDefinition = {
    iconName: "arrowLineUpRightSmall",
    svgPathData: {duotone: ["m8.52 11.47 3.67-3.67H9.05a.75.75 0 0 1 0-1.5H14a.75.75 0 0 1 .75.75V12a.75.75 0 0 1-1.5 0V8.861L9.58 12.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-1.508 6.28a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],fill: ["m8.52 11.47 3.67-3.67H9.05a.75.75 0 0 1 0-1.5H14a.75.75 0 0 1 .75.75V12a.75.75 0 0 1-1.5 0V8.861L9.58 12.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-1.508 6.28a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],line: ["m8.52 11.47 3.67-3.67H9.05a.75.75 0 0 1 0-1.5H14a.75.75 0 0 1 .75.75V12a.75.75 0 0 1-1.5 0V8.861L9.58 12.53a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-1.508 6.28a.75.75 0 0 1 0-1.5h10a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowLineUpRightSmall;
