// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLeft : DbIconDefinition = {
    iconName: "arrowLeft",
    svgPathData: {duotone: ["M11.53 18.53a.75.75 0 0 1-1.06 0l-6-6a.75.75 0 0 1 0-1.06l6-6a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4.72 4.72H19a.75.75 0 0 1 0 1.5H6.81l4.72 4.72a.75.75 0 0 1 0 1.06Z"],fill: ["M11.53 18.53a.75.75 0 0 1-1.06 0l-6-6a.75.75 0 0 1 0-1.06l6-6a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4.72 4.72H19a.75.75 0 0 1 0 1.5H6.81l4.72 4.72a.75.75 0 0 1 0 1.06Z"],line: ["M11.53 18.53a.75.75 0 0 1-1.06 0l-6-6a.75.75 0 0 1 0-1.06l6-6a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4.72 4.72H19a.75.75 0 0 1 0 1.5H6.81l4.72 4.72a.75.75 0 0 1 0 1.06Z"],}
}

export default dbArrowLeft;
