// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowReturnRightUp : DbIconDefinition = {
    iconName: "arrowReturnRightUp",
    svgPathData: {duotone: ["M5.75 15a5.25 5.25 0 0 0 10.5 0V4.81l-2.72 2.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l4-4a.75.75 0 0 1 1.06 0l4 4a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-2.72-2.72V15a6.75 6.75 0 1 1-13.5 0v-4a.75.75 0 0 1 1.5 0Z"],fill: ["M5.75 15a5.25 5.25 0 0 0 10.5 0V4.81l-2.72 2.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l4-4a.75.75 0 0 1 1.06 0l4 4a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-2.72-2.72V15a6.75 6.75 0 1 1-13.5 0v-4a.75.75 0 0 1 1.5 0Z"],line: ["M5.75 15a5.25 5.25 0 0 0 10.5 0V4.81l-2.72 2.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l4-4a.75.75 0 0 1 1.06 0l4 4a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-2.72-2.72V15a6.75 6.75 0 1 1-13.5 0v-4a.75.75 0 0 1 1.5 0Z"],}
}

export default dbArrowReturnRightUp;
