// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowDownSmall : DbIconDefinition = {
    iconName: "arrowDownSmall",
    svgPathData: {duotone: ["M7.47 12.47a.75.75 0 0 1 1.06 0l2.72 2.72V7a.75.75 0 0 1 1.5 0v8.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.75.75 0 0 1 0-1.06Z"],fill: ["M7.47 12.47a.75.75 0 0 1 1.06 0l2.72 2.72V7a.75.75 0 0 1 1.5 0v8.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.75.75 0 0 1 0-1.06Z"],line: ["M7.47 12.47a.75.75 0 0 1 1.06 0l2.72 2.72V7a.75.75 0 0 1 1.5 0v8.19l2.72-2.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-4 4a.75.75 0 0 1-1.06 0l-4-4a.75.75 0 0 1 0-1.06Z"],}
}

export default dbArrowDownSmall;
