// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowDownLeft : DbIconDefinition = {
    iconName: "arrowDownLeft",
    svgPathData: {duotone: ["M15.5 17.25a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75V8.5a.75.75 0 0 1 1.5 0v7.69L17.47 5.47a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734L7.81 17.25Z"],fill: ["M15.5 17.25a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75V8.5a.75.75 0 0 1 1.5 0v7.69L17.47 5.47a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734L7.81 17.25Z"],line: ["M15.5 17.25a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75V8.5a.75.75 0 0 1 1.5 0v7.69L17.47 5.47a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734L7.81 17.25Z"],}
}

export default dbArrowDownLeft;
