// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerRightSplit : DbIconDefinition = {
    iconName: "arrowsCornerRightSplit",
    svgPathData: {duotone: ["M13 4.25h6a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V6.81l-3.72 3.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l3.72-3.72H13a.75.75 0 0 1 0-1.5Zm-2 15.5H5a.75.75 0 0 1-.75-.75v-6a.75.75 0 0 1 1.5 0v4.19l3.72-3.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3.72 3.72H11a.75.75 0 0 1 0 1.5Z"],fill: ["M13 4.25h6a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V6.81l-3.72 3.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l3.72-3.72H13a.75.75 0 0 1 0-1.5Zm-2 15.5H5a.75.75 0 0 1-.75-.75v-6a.75.75 0 0 1 1.5 0v4.19l3.72-3.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3.72 3.72H11a.75.75 0 0 1 0 1.5Z"],line: ["M13 4.25h6a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V6.81l-3.72 3.72a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l3.72-3.72H13a.75.75 0 0 1 0-1.5Zm-2 15.5H5a.75.75 0 0 1-.75-.75v-6a.75.75 0 0 1 1.5 0v4.19l3.72-3.72a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734l-3.72 3.72H11a.75.75 0 0 1 0 1.5Z"],}
}

export default dbArrowsCornerRightSplit;
