// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowLineRightSmall : DbIconDefinition = {
    iconName: "arrowLineRightSmall",
    svgPathData: {duotone: ["M7 11.25h5.19L9.97 9.03a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3.5 3.5a.75.75 0 0 1 0 1.06l-3.5 3.5a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.22-2.22H7a.75.75 0 0 1 0-1.5ZM17.75 17a.75.75 0 0 1-1.5 0V7a.75.75 0 0 1 1.5 0Z"],fill: ["M7 11.25h5.19L9.97 9.03a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3.5 3.5a.75.75 0 0 1 0 1.06l-3.5 3.5a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.22-2.22H7a.75.75 0 0 1 0-1.5ZM17.75 17a.75.75 0 0 1-1.5 0V7a.75.75 0 0 1 1.5 0Z"],line: ["M7 11.25h5.19L9.97 9.03a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l3.5 3.5a.75.75 0 0 1 0 1.06l-3.5 3.5a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734l2.22-2.22H7a.75.75 0 0 1 0-1.5ZM17.75 17a.75.75 0 0 1-1.5 0V7a.75.75 0 0 1 1.5 0Z"],}
}

export default dbArrowLineRightSmall;
