// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowsCornerRight : DbIconDefinition = {
    iconName: "arrowsCornerRight",
    svgPathData: {duotone: ["M13 5.75a.75.75 0 0 1 0-1.5h6a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V6.81L6.81 18.25H11a.75.75 0 0 1 0 1.5H5a.75.75 0 0 1-.75-.75v-6a.75.75 0 0 1 1.5 0v4.19L17.19 5.75Z"],fill: ["M13 5.75a.75.75 0 0 1 0-1.5h6a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V6.81L6.81 18.25H11a.75.75 0 0 1 0 1.5H5a.75.75 0 0 1-.75-.75v-6a.75.75 0 0 1 1.5 0v4.19L17.19 5.75Z"],line: ["M13 5.75a.75.75 0 0 1 0-1.5h6a.75.75 0 0 1 .75.75v6a.75.75 0 0 1-1.5 0V6.81L6.81 18.25H11a.75.75 0 0 1 0 1.5H5a.75.75 0 0 1-.75-.75v-6a.75.75 0 0 1 1.5 0v4.19L17.19 5.75Z"],}
}

export default dbArrowsCornerRight;
