// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbArrowTrendUpSmall : DbIconDefinition = {
    iconName: "arrowTrendUpSmall",
    svgPathData: {duotone: ["M6.49 15.55a.75.75 0 0 1-.04-1.06l2.222-2.4a2.263 2.263 0 0 1 3.323 0 .766.766 0 0 0 1.121 0l2.167-2.34h-1.616a.75.75 0 0 1 0-1.5H17a.75.75 0 0 1 .75.75v3.6a.75.75 0 0 1-1.5 0v-1.686l-2.033 2.196a2.263 2.263 0 0 1-3.323 0 .766.766 0 0 0-1.121 0l-2.223 2.4a.75.75 0 0 1-1.06.04Z"],fill: ["M6.49 15.55a.75.75 0 0 1-.04-1.06l2.222-2.4a2.263 2.263 0 0 1 3.323 0 .766.766 0 0 0 1.121 0l2.167-2.34h-1.616a.75.75 0 0 1 0-1.5H17a.75.75 0 0 1 .75.75v3.6a.75.75 0 0 1-1.5 0v-1.686l-2.033 2.196a2.263 2.263 0 0 1-3.323 0 .766.766 0 0 0-1.121 0l-2.223 2.4a.75.75 0 0 1-1.06.04Z"],line: ["M6.49 15.55a.75.75 0 0 1-.04-1.06l2.222-2.4a2.263 2.263 0 0 1 3.323 0 .766.766 0 0 0 1.121 0l2.167-2.34h-1.616a.75.75 0 0 1 0-1.5H17a.75.75 0 0 1 .75.75v3.6a.75.75 0 0 1-1.5 0v-1.686l-2.033 2.196a2.263 2.263 0 0 1-3.323 0 .766.766 0 0 0-1.121 0l-2.223 2.4a.75.75 0 0 1-1.06.04Z"],}
}

export default dbArrowTrendUpSmall;
