// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbAtSmall : DbIconDefinition = {
    iconName: "atSmall",
    svgPathData: {duotone: ["M15 12a3 3 0 1 1-6 0 3 3 0 1 1 6 0Z","M5.75 12a6.25 6.25 0 0 0 9.027 5.601.75.75 0 1 1 .668 1.343A7.75 7.75 0 1 1 19.75 12v1a2.75 2.75 0 0 1-5.013 1.563A3.75 3.75 0 1 1 14.25 9a.75.75 0 0 1 1.5 0v4a1.25 1.25 0 0 0 2.5 0v-1a6.25 6.25 0 1 0-12.5 0ZM12 9.75a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5Z"],fill: ["M5.75 12a6.25 6.25 0 0 0 9.027 5.601.75.75 0 1 1 .668 1.343A7.75 7.75 0 1 1 19.75 12v1a2.75 2.75 0 0 1-5.013 1.563A3.75 3.75 0 1 1 14.25 9a.75.75 0 0 1 1.5 0v4a1.25 1.25 0 0 0 2.5 0v-1a6.25 6.25 0 1 0-12.5 0ZM12 9.75a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5Z"],line: ["M5.75 12a6.25 6.25 0 0 0 9.027 5.601.75.75 0 1 1 .668 1.343A7.75 7.75 0 1 1 19.75 12v1a2.75 2.75 0 0 1-5.013 1.563A3.75 3.75 0 1 1 14.25 9a.75.75 0 0 1 1.5 0v4a1.25 1.25 0 0 0 2.5 0v-1a6.25 6.25 0 1 0-12.5 0ZM12 9.75a2.25 2.25 0 1 0 0 4.5 2.25 2.25 0 0 0 0-4.5Z"],}
}

export default dbAtSmall;
