// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbBracketsSquareSmall : DbIconDefinition = {
    iconName: "bracketsSquareSmall",
    svgPathData: {duotone: ["M5.25 9A3.75 3.75 0 0 1 9 5.25a.75.75 0 0 1 0 1.5A2.25 2.25 0 0 0 6.75 9v6A2.25 2.25 0 0 0 9 17.25a.75.75 0 0 1 0 1.5A3.75 3.75 0 0 1 5.25 15Zm9-3a.75.75 0 0 1 .75-.75A3.75 3.75 0 0 1 18.75 9v6A3.75 3.75 0 0 1 15 18.75a.75.75 0 0 1 0-1.5A2.25 2.25 0 0 0 17.25 15V9A2.25 2.25 0 0 0 15 6.75a.75.75 0 0 1-.75-.75Z"],fill: ["M5.25 9A3.75 3.75 0 0 1 9 5.25a.75.75 0 0 1 0 1.5A2.25 2.25 0 0 0 6.75 9v6A2.25 2.25 0 0 0 9 17.25a.75.75 0 0 1 0 1.5A3.75 3.75 0 0 1 5.25 15Zm9-3a.75.75 0 0 1 .75-.75A3.75 3.75 0 0 1 18.75 9v6A3.75 3.75 0 0 1 15 18.75a.75.75 0 0 1 0-1.5A2.25 2.25 0 0 0 17.25 15V9A2.25 2.25 0 0 0 15 6.75a.75.75 0 0 1-.75-.75Z"],line: ["M5.25 9A3.75 3.75 0 0 1 9 5.25a.75.75 0 0 1 0 1.5A2.25 2.25 0 0 0 6.75 9v6A2.25 2.25 0 0 0 9 17.25a.75.75 0 0 1 0 1.5A3.75 3.75 0 0 1 5.25 15Zm9-3a.75.75 0 0 1 .75-.75A3.75 3.75 0 0 1 18.75 9v6A3.75 3.75 0 0 1 15 18.75a.75.75 0 0 1 0-1.5A2.25 2.25 0 0 0 17.25 15V9A2.25 2.25 0 0 0 15 6.75a.75.75 0 0 1-.75-.75Z"],}
}

export default dbBracketsSquareSmall;
