// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronRightSmall : DbIconDefinition = {
    iconName: "chevronRightSmall",
    svgPathData: {duotone: ["M10.47 16.53a.75.75 0 0 1 0-1.06L13.94 12l-3.47-3.47a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0Z"],fill: ["M10.47 16.53a.75.75 0 0 1 0-1.06L13.94 12l-3.47-3.47a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0Z"],line: ["M10.47 16.53a.75.75 0 0 1 0-1.06L13.94 12l-3.47-3.47a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4 4a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0Z"],}
}

export default dbChevronRightSmall;
