// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronDown : DbIconDefinition = {
    iconName: "chevronDown",
    svgPathData: {duotone: ["M12.53 15.53a.75.75 0 0 1-1.06 0l-6-6a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018L12 13.94l5.47-5.47a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734Z"],fill: ["M12.53 15.53a.75.75 0 0 1-1.06 0l-6-6a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018L12 13.94l5.47-5.47a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734Z"],line: ["M12.53 15.53a.75.75 0 0 1-1.06 0l-6-6a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018L12 13.94l5.47-5.47a.749.749 0 0 1 1.275.326.749.749 0 0 1-.215.734Z"],}
}

export default dbChevronDown;
