// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronDownSmall : DbIconDefinition = {
    iconName: "chevronDownSmall",
    svgPathData: {duotone: ["M16.53 10.47a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0l-4-4a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215L12 13.94l3.47-3.47a.75.75 0 0 1 1.06 0Z"],fill: ["M16.53 10.47a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0l-4-4a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215L12 13.94l3.47-3.47a.75.75 0 0 1 1.06 0Z"],line: ["M16.53 10.47a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0l-4-4a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215L12 13.94l3.47-3.47a.75.75 0 0 1 1.06 0Z"],}
}

export default dbChevronDownSmall;
