// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronRight : DbIconDefinition = {
    iconName: "chevronRight",
    svgPathData: {duotone: ["M9.47 5.47a.75.75 0 0 1 1.06 0l6 6a.75.75 0 0 1 0 1.06l-6 6a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734L14.94 12 9.47 6.53a.75.75 0 0 1 0-1.06Z"],fill: ["M9.47 5.47a.75.75 0 0 1 1.06 0l6 6a.75.75 0 0 1 0 1.06l-6 6a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734L14.94 12 9.47 6.53a.75.75 0 0 1 0-1.06Z"],line: ["M9.47 5.47a.75.75 0 0 1 1.06 0l6 6a.75.75 0 0 1 0 1.06l-6 6a.749.749 0 0 1-1.275-.326.749.749 0 0 1 .215-.734L14.94 12 9.47 6.53a.75.75 0 0 1 0-1.06Z"],}
}

export default dbChevronRight;
