// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronLeft : DbIconDefinition = {
    iconName: "chevronLeft",
    svgPathData: {duotone: ["M14.53 5.47a.75.75 0 0 1 0 1.06L9.06 12l5.47 5.47a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-6-6a.75.75 0 0 1 0-1.06l6-6a.75.75 0 0 1 1.06 0Z"],fill: ["M14.53 5.47a.75.75 0 0 1 0 1.06L9.06 12l5.47 5.47a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-6-6a.75.75 0 0 1 0-1.06l6-6a.75.75 0 0 1 1.06 0Z"],line: ["M14.53 5.47a.75.75 0 0 1 0 1.06L9.06 12l5.47 5.47a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-6-6a.75.75 0 0 1 0-1.06l6-6a.75.75 0 0 1 1.06 0Z"],}
}

export default dbChevronLeft;
