// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbCheck : DbIconDefinition = {
    iconName: "check",
    svgPathData: {duotone: ["M20.507 5.447a.75.75 0 0 1 .046 1.06l-11 12a.751.751 0 0 1-1.083.023l-5-5a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4.446 4.446L19.447 5.493a.75.75 0 0 1 1.06-.046Z"],fill: ["M20.507 5.447a.75.75 0 0 1 .046 1.06l-11 12a.751.751 0 0 1-1.083.023l-5-5a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4.446 4.446L19.447 5.493a.75.75 0 0 1 1.06-.046Z"],line: ["M20.507 5.447a.75.75 0 0 1 .046 1.06l-11 12a.751.751 0 0 1-1.083.023l-5-5a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l4.446 4.446L19.447 5.493a.75.75 0 0 1 1.06-.046Z"],}
}

export default dbCheck;
