// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronUpSmall : DbIconDefinition = {
    iconName: "chevronUpSmall",
    svgPathData: {duotone: ["M16.53 14.53a.75.75 0 0 1-1.06 0L12 11.06l-3.47 3.47a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06Z"],fill: ["M16.53 14.53a.75.75 0 0 1-1.06 0L12 11.06l-3.47 3.47a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06Z"],line: ["M16.53 14.53a.75.75 0 0 1-1.06 0L12 11.06l-3.47 3.47a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l4-4a.75.75 0 0 1 1.06 0l4 4a.75.75 0 0 1 0 1.06Z"],}
}

export default dbChevronUpSmall;
