// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronLeftSmall : DbIconDefinition = {
    iconName: "chevronLeftSmall",
    svgPathData: {duotone: ["M13.53 7.47a.75.75 0 0 1 0 1.06L10.06 12l3.47 3.47a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-4-4a.75.75 0 0 1 0-1.06l4-4a.75.75 0 0 1 1.06 0Z"],fill: ["M13.53 7.47a.75.75 0 0 1 0 1.06L10.06 12l3.47 3.47a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-4-4a.75.75 0 0 1 0-1.06l4-4a.75.75 0 0 1 1.06 0Z"],line: ["M13.53 7.47a.75.75 0 0 1 0 1.06L10.06 12l3.47 3.47a.751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018l-4-4a.75.75 0 0 1 0-1.06l4-4a.75.75 0 0 1 1.06 0Z"],}
}

export default dbChevronLeftSmall;
