// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbChevronUp : DbIconDefinition = {
    iconName: "chevronUp",
    svgPathData: {duotone: ["m12.53 8.47 6 6a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L12 10.06l-5.47 5.47a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l6-6a.75.75 0 0 1 1.06 0Z"],fill: ["m12.53 8.47 6 6a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L12 10.06l-5.47 5.47a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l6-6a.75.75 0 0 1 1.06 0Z"],line: ["m12.53 8.47 6 6a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215L12 10.06l-5.47 5.47a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042l6-6a.75.75 0 0 1 1.06 0Z"],}
}

export default dbChevronUp;
