// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbCheckSmall : DbIconDefinition = {
    iconName: "checkSmall",
    svgPathData: {duotone: ["M18.494 7.436a.75.75 0 0 1 .07 1.058l-7 8a.75.75 0 0 1-1.094.036l-3-3a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l2.434 2.433 6.472-7.397a.75.75 0 0 1 1.058-.07Z"],fill: ["M18.494 7.436a.75.75 0 0 1 .07 1.058l-7 8a.75.75 0 0 1-1.094.036l-3-3a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l2.434 2.433 6.472-7.397a.75.75 0 0 1 1.058-.07Z"],line: ["M18.494 7.436a.75.75 0 0 1 .07 1.058l-7 8a.75.75 0 0 1-1.094.036l-3-3a.749.749 0 0 1 .326-1.275.749.749 0 0 1 .734.215l2.434 2.433 6.472-7.397a.75.75 0 0 1 1.058-.07Z"],}
}

export default dbCheckSmall;
