// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbCircleNotch : DbIconDefinition = {
    iconName: "circleNotch",
    svgPathData: {duotone: ["M11.25 3a.75.75 0 0 1 .75-.75A9.75 9.75 0 0 1 21.75 12a9.75 9.75 0 0 1-18.038 5.139 9.75 9.75 0 0 1-.448-9.473.749.749 0 0 1 1.343.668A8.25 8.25 0 1 0 12 3.75a.75.75 0 0 1-.75-.75Z"],fill: ["M11.25 3a.75.75 0 0 1 .75-.75A9.75 9.75 0 0 1 21.75 12a9.75 9.75 0 0 1-18.038 5.139 9.75 9.75 0 0 1-.448-9.473.749.749 0 0 1 1.343.668A8.25 8.25 0 1 0 12 3.75a.75.75 0 0 1-.75-.75Z"],line: ["M11.25 3a.75.75 0 0 1 .75-.75A9.75 9.75 0 0 1 21.75 12a9.75 9.75 0 0 1-18.038 5.139 9.75 9.75 0 0 1-.448-9.473.749.749 0 0 1 1.343.668A8.25 8.25 0 1 0 12 3.75a.75.75 0 0 1-.75-.75Z"],}
}

export default dbCircleNotch;
