// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbCloud : DbIconDefinition = {
    iconName: "cloud",
    svgPathData: {duotone: ["M12 4a5 5 0 0 0-5 5 5 5 0 0 0 0 10h10a5 5 0 0 0 0-10 5 5 0 0 0-5-5Z","M12 4.75a4.248 4.248 0 0 0-3.682 2.126.75.75 0 0 1-1.298-.752 5.75 5.75 0 0 1 10.687 2.169A5.75 5.75 0 0 1 17 19.75H7A5.75 5.75 0 1 1 9.3 8.729a.75.75 0 0 1-.6 1.374A4.251 4.251 0 1 0 7 18.25h10a4.25 4.25 0 0 0 0-8.5.75.75 0 0 1-.75-.75A4.25 4.25 0 0 0 12 4.75Z"],fill: ["M12 3.25a5.751 5.751 0 0 1 5.707 5.043A5.75 5.75 0 0 1 17 19.75H7a5.751 5.751 0 0 1-.707-11.457A5.751 5.751 0 0 1 12 3.25Z"],line: ["M12 4.75a4.248 4.248 0 0 0-3.682 2.126.75.75 0 0 1-1.298-.752 5.75 5.75 0 0 1 10.687 2.169A5.75 5.75 0 0 1 17 19.75H7A5.75 5.75 0 1 1 9.3 8.729a.75.75 0 0 1-.6 1.374A4.251 4.251 0 1 0 7 18.25h10a4.25 4.25 0 0 0 0-8.5.75.75 0 0 1-.75-.75A4.25 4.25 0 0 0 12 4.75Z"],}
}

export default dbCloud;
