// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbDots3HorizontalCircle : DbIconDefinition = {
    iconName: "dots3HorizontalCircle",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM3.75 12a8.25 8.25 0 1 0 16.5 0 8.25 8.25 0 0 0-16.5 0ZM7 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 7 13.5Zm3.5-1.5a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 10.5 12Zm5 0a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 15.5 12Z"],fill: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM7 13.5a1.5 1.5 0 1 0-.001-3.001A1.5 1.5 0 0 0 7 13.5Zm3.5-1.5a1.5 1.5 0 1 0 3.001-.001A1.5 1.5 0 0 0 10.5 12Zm6.5 1.5a1.5 1.5 0 1 0-.001-3.001A1.5 1.5 0 0 0 17 13.5Z"],line: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM3.75 12a8.25 8.25 0 1 0 16.5 0 8.25 8.25 0 0 0-16.5 0ZM7 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 7 13.5Zm3.5-1.5a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 10.5 12Zm5 0a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 15.5 12Z"],}
}

export default dbDots3HorizontalCircle;
