// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbDots3Vertical : DbIconDefinition = {
    iconName: "dots3Vertical",
    svgPathData: {duotone: ["M12 16.25a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5ZM9.25 5a2.75 2.75 0 1 1 5.5 0 2.75 2.75 0 0 1-5.5 0Zm0 7a2.75 2.75 0 1 1 5.5 0 2.75 2.75 0 0 1-5.5 0ZM12 10.75a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5Zm0-7a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5ZM10.75 19a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0Z"],fill: ["M9.25 19a2.75 2.75 0 1 1 5.5 0 2.75 2.75 0 0 1-5.5 0ZM12 2.25a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5Zm0 7a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5Z"],line: ["M12 16.25a2.75 2.75 0 1 1 0 5.5 2.75 2.75 0 0 1 0-5.5ZM9.25 5a2.75 2.75 0 1 1 5.5 0 2.75 2.75 0 0 1-5.5 0Zm0 7a2.75 2.75 0 1 1 5.5 0 2.75 2.75 0 0 1-5.5 0ZM12 10.75a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5Zm0-7a1.25 1.25 0 1 0 0 2.5 1.25 1.25 0 0 0 0-2.5ZM10.75 19a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 0 0-2.5 0Z"],}
}

export default dbDots3Vertical;
