// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbDots3VerticalSmall : DbIconDefinition = {
    iconName: "dots3VerticalSmall",
    svgPathData: {duotone: ["M13.5 7a1.5 1.5 0 1 1-3.001-.001A1.5 1.5 0 0 1 13.5 7Zm0 5a1.5 1.5 0 1 1-3.001-.001A1.5 1.5 0 0 1 13.5 12ZM12 18.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 18.5Z"],fill: ["M13.5 7a1.5 1.5 0 1 1-3.001-.001A1.5 1.5 0 0 1 13.5 7Zm0 5a1.5 1.5 0 1 1-3.001-.001A1.5 1.5 0 0 1 13.5 12ZM12 18.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 18.5Z"],line: ["M13.5 7a1.5 1.5 0 1 1-3.001-.001A1.5 1.5 0 0 1 13.5 7Zm0 5a1.5 1.5 0 1 1-3.001-.001A1.5 1.5 0 0 1 13.5 12ZM12 18.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 18.5Z"],}
}

export default dbDots3VerticalSmall;
