// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbDots3HorizontalSmall : DbIconDefinition = {
    iconName: "dots3HorizontalSmall",
    svgPathData: {duotone: ["M12 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 13.5ZM5.5 12a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 5.5 12ZM17 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 17 13.5Z"],fill: ["M12 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 13.5ZM5.5 12a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 5.5 12ZM17 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 17 13.5Z"],line: ["M12 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 13.5ZM5.5 12a1.5 1.5 0 1 1 3.001.001A1.5 1.5 0 0 1 5.5 12ZM17 13.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 17 13.5Z"],}
}

export default dbDots3HorizontalSmall;
