// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbExclamationSmall : DbIconDefinition = {
    iconName: "exclamationSmall",
    svgPathData: {duotone: ["M12.75 7v6a.75.75 0 0 1-1.5 0V7a.75.75 0 0 1 1.5 0ZM12 18a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],fill: ["M12.75 7v6a.75.75 0 0 1-1.5 0V7a.75.75 0 0 1 1.5 0ZM12 18a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],line: ["M12.75 7v6a.75.75 0 0 1-1.5 0V7a.75.75 0 0 1 1.5 0ZM12 18a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],}
}

export default dbExclamationSmall;
