// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbFaceNeutral : DbIconDefinition = {
    iconName: "faceNeutral",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM3.75 12a8.25 8.25 0 1 0 16.5 0 8.25 8.25 0 0 0-16.5 0ZM9 14.25h6a.75.75 0 0 1 0 1.5H9a.75.75 0 0 1 0-1.5ZM10 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm5 1a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],fill: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM8.25 15c0 .414.336.75.75.75h6a.75.75 0 0 0 0-1.5H9a.75.75 0 0 0-.75.75ZM16 9a1 1 0 1 0-2 0 1 1 0 0 0 2 0Zm-7 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"],line: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM3.75 12a8.25 8.25 0 1 0 16.5 0 8.25 8.25 0 0 0-16.5 0ZM9 14.25h6a.75.75 0 0 1 0 1.5H9a.75.75 0 0 1 0-1.5ZM10 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm5 1a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],}
}

export default dbFaceNeutral;
