// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbFilterLines : DbIconDefinition = {
    iconName: "filterLines",
    svgPathData: {duotone: ["M4 4.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM5.25 12a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75Zm3 7a.75.75 0 0 1 .75-.75h6a.75.75 0 0 1 0 1.5H9a.75.75 0 0 1-.75-.75Z"],fill: ["M4 4.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM5.25 12a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75Zm3 7a.75.75 0 0 1 .75-.75h6a.75.75 0 0 1 0 1.5H9a.75.75 0 0 1-.75-.75Z"],line: ["M4 4.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM5.25 12a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75Zm3 7a.75.75 0 0 1 .75-.75h6a.75.75 0 0 1 0 1.5H9a.75.75 0 0 1-.75-.75Z"],}
}

export default dbFilterLines;
