// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbFormatItalic : DbIconDefinition = {
    iconName: "formatItalic",
    svgPathData: {duotone: ["M8.25 4A.75.75 0 0 1 9 3.25h10a.75.75 0 0 1 0 1.5h-4.414l-3.625 14.5H15a.75.75 0 0 1 0 1.5H5a.75.75 0 0 1 0-1.5h4.414l3.625-14.5H9A.75.75 0 0 1 8.25 4Z"],fill: ["M8.25 4A.75.75 0 0 1 9 3.25h10a.75.75 0 0 1 0 1.5h-4.414l-3.625 14.5H15a.75.75 0 0 1 0 1.5H5a.75.75 0 0 1 0-1.5h4.414l3.625-14.5H9A.75.75 0 0 1 8.25 4Z"],line: ["M8.25 4A.75.75 0 0 1 9 3.25h10a.75.75 0 0 1 0 1.5h-4.414l-3.625 14.5H15a.75.75 0 0 1 0 1.5H5a.75.75 0 0 1 0-1.5h4.414l3.625-14.5H9A.75.75 0 0 1 8.25 4Z"],}
}

export default dbFormatItalic;
