// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbFormatUnderline : DbIconDefinition = {
    iconName: "formatUnderline",
    svgPathData: {duotone: ["M7 3.25a.75.75 0 0 1 .75.75v7a4.25 4.25 0 0 0 8.5 0V4a.75.75 0 0 1 1.5 0v7a5.75 5.75 0 1 1-11.5 0V4A.75.75 0 0 1 7 3.25ZM5.25 20a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75Z"],fill: ["M7 3.25a.75.75 0 0 1 .75.75v7a4.25 4.25 0 0 0 8.5 0V4a.75.75 0 0 1 1.5 0v7a5.75 5.75 0 1 1-11.5 0V4A.75.75 0 0 1 7 3.25ZM5.25 20a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75Z"],line: ["M7 3.25a.75.75 0 0 1 .75.75v7a4.25 4.25 0 0 0 8.5 0V4a.75.75 0 0 1 1.5 0v7a5.75 5.75 0 1 1-11.5 0V4A.75.75 0 0 1 7 3.25ZM5.25 20a.75.75 0 0 1 .75-.75h12a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.75-.75Z"],}
}

export default dbFormatUnderline;
