// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbFormatBold : DbIconDefinition = {
    iconName: "formatBold",
    svgPathData: {duotone: ["M6 3.25h6a4.751 4.751 0 0 1 3.29 8.177A4.751 4.751 0 0 1 14 20.75H6a.75.75 0 0 1-.75-.75V4A.75.75 0 0 1 6 3.25Zm.75 16H14a3.25 3.25 0 1 0 0-6.5H6.75Zm0-8H12a3.25 3.25 0 1 0 0-6.5H6.75Z"],fill: ["M6 3.25h6a4.751 4.751 0 0 1 3.29 8.177A4.751 4.751 0 0 1 14 20.75H6a.75.75 0 0 1-.75-.75V4A.75.75 0 0 1 6 3.25Zm.75 16H14a3.25 3.25 0 1 0 0-6.5H6.75Zm0-8H12a3.25 3.25 0 1 0 0-6.5H6.75Z"],line: ["M6 3.25h6a4.751 4.751 0 0 1 3.29 8.177A4.751 4.751 0 0 1 14 20.75H6a.75.75 0 0 1-.75-.75V4A.75.75 0 0 1 6 3.25Zm.75 16H14a3.25 3.25 0 1 0 0-6.5H6.75Zm0-8H12a3.25 3.25 0 1 0 0-6.5H6.75Z"],}
}

export default dbFormatBold;
