// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbHashtagStraightSmall : DbIconDefinition = {
    iconName: "hashtagStraightSmall",
    svgPathData: {duotone: ["M9.75 6v2.25h4.5V6a.75.75 0 0 1 1.5 0v2.25H18a.75.75 0 0 1 0 1.5h-2.25v4.5H18a.75.75 0 0 1 0 1.5h-2.25V18a.75.75 0 0 1-1.5 0v-2.25h-4.5V18a.75.75 0 0 1-1.5 0v-2.25H6a.75.75 0 0 1 0-1.5h2.25v-4.5H6a.75.75 0 0 1 0-1.5h2.25V6a.75.75 0 0 1 1.5 0Zm4.5 3.75h-4.5v4.5h4.5Z"],fill: ["M9.75 6v2.25h4.5V6a.75.75 0 0 1 1.5 0v2.25H18a.75.75 0 0 1 0 1.5h-2.25v4.5H18a.75.75 0 0 1 0 1.5h-2.25V18a.75.75 0 0 1-1.5 0v-2.25h-4.5V18a.75.75 0 0 1-1.5 0v-2.25H6a.75.75 0 0 1 0-1.5h2.25v-4.5H6a.75.75 0 0 1 0-1.5h2.25V6a.75.75 0 0 1 1.5 0Zm4.5 3.75h-4.5v4.5h4.5Z"],line: ["M9.75 6v2.25h4.5V6a.75.75 0 0 1 1.5 0v2.25H18a.75.75 0 0 1 0 1.5h-2.25v4.5H18a.75.75 0 0 1 0 1.5h-2.25V18a.75.75 0 0 1-1.5 0v-2.25h-4.5V18a.75.75 0 0 1-1.5 0v-2.25H6a.75.75 0 0 1 0-1.5h2.25v-4.5H6a.75.75 0 0 1 0-1.5h2.25V6a.75.75 0 0 1 1.5 0Zm4.5 3.75h-4.5v4.5h4.5Z"],}
}

export default dbHashtagStraightSmall;
