// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbHashtagStraight : DbIconDefinition = {
    iconName: "hashtagStraight",
    svgPathData: {duotone: ["M8.75 4v3.25h6.5V4a.75.75 0 0 1 1.5 0v3.25H20a.75.75 0 0 1 0 1.5h-3.25v6.5H20a.75.75 0 0 1 0 1.5h-3.25V20a.75.75 0 0 1-1.5 0v-3.25h-6.5V20a.75.75 0 0 1-1.5 0v-3.25H4a.75.75 0 0 1 0-1.5h3.25v-6.5H4a.75.75 0 0 1 0-1.5h3.25V4a.75.75 0 0 1 1.5 0Zm6.5 4.75h-6.5v6.5h6.5Z"],fill: ["M8.75 4v3.25h6.5V4a.75.75 0 0 1 1.5 0v3.25H20a.75.75 0 0 1 0 1.5h-3.25v6.5H20a.75.75 0 0 1 0 1.5h-3.25V20a.75.75 0 0 1-1.5 0v-3.25h-6.5V20a.75.75 0 0 1-1.5 0v-3.25H4a.75.75 0 0 1 0-1.5h3.25v-6.5H4a.75.75 0 0 1 0-1.5h3.25V4a.75.75 0 0 1 1.5 0Zm6.5 4.75h-6.5v6.5h6.5Z"],line: ["M8.75 4v3.25h6.5V4a.75.75 0 0 1 1.5 0v3.25H20a.75.75 0 0 1 0 1.5h-3.25v6.5H20a.75.75 0 0 1 0 1.5h-3.25V20a.75.75 0 0 1-1.5 0v-3.25h-6.5V20a.75.75 0 0 1-1.5 0v-3.25H4a.75.75 0 0 1 0-1.5h3.25v-6.5H4a.75.75 0 0 1 0-1.5h3.25V4a.75.75 0 0 1 1.5 0Zm6.5 4.75h-6.5v6.5h6.5Z"],}
}

export default dbHashtagStraight;
