// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbHeadphones : DbIconDefinition = {
    iconName: "headphones",
    svgPathData: {duotone: ["M3 16a3 3 0 1 1 6 0v2a3 3 0 1 1-6 0v-2Zm12 0a3 3 0 1 1 6 0v2a3 3 0 1 1-6 0v-2Z","M12 2.25A9.75 9.75 0 0 1 21.75 12v6a3.75 3.75 0 0 1-7.5 0v-2a3.75 3.75 0 0 1 6-3v-1a8.25 8.25 0 0 0-16.5 0v1a3.75 3.75 0 0 1 6 3v2a3.75 3.75 0 0 1-7.5 0v-6A9.75 9.75 0 0 1 12 2.25ZM20.25 16a2.25 2.25 0 1 0-4.5 0v2a2.25 2.25 0 1 0 4.5 0Zm-16.5 0v2a2.25 2.25 0 1 0 4.5 0v-2a2.25 2.25 0 1 0-4.5 0Z"],fill: ["M12 2.25A9.75 9.75 0 0 1 21.75 12v6a3.75 3.75 0 0 1-7.5 0v-2a3.75 3.75 0 0 1 6-3v-1a8.25 8.25 0 0 0-16.5 0v1a3.75 3.75 0 0 1 6 3v2a3.75 3.75 0 0 1-7.5 0v-6A9.75 9.75 0 0 1 12 2.25Z"],line: ["M12 2.25A9.75 9.75 0 0 1 21.75 12v6a3.75 3.75 0 0 1-7.5 0v-2a3.75 3.75 0 0 1 6-3v-1a8.25 8.25 0 0 0-16.5 0v1a3.75 3.75 0 0 1 6 3v2a3.75 3.75 0 0 1-7.5 0v-6A9.75 9.75 0 0 1 12 2.25ZM20.25 16a2.25 2.25 0 1 0-4.5 0v2a2.25 2.25 0 1 0 4.5 0Zm-16.5 0v2a2.25 2.25 0 1 0 4.5 0v-2a2.25 2.25 0 1 0-4.5 0Z"],}
}

export default dbHeadphones;
