// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbInfoCircle : DbIconDefinition = {
    iconName: "infoCircle",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM3.75 12a8.25 8.25 0 1 0 16.5 0 8.25 8.25 0 0 0-16.5 0ZM12 10.25a.75.75 0 0 1 .75.75v5a.75.75 0 0 1-1.5 0v-5a.75.75 0 0 1 .75-.75ZM13 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"],fill: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25Zm.75 8.75a.75.75 0 0 0-1.5 0v5a.75.75 0 0 0 1.5 0ZM13 8a1 1 0 1 0-2 0 1 1 0 0 0 2 0Z"],line: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25ZM3.75 12a8.25 8.25 0 1 0 16.5 0 8.25 8.25 0 0 0-16.5 0ZM12 10.25a.75.75 0 0 1 .75.75v5a.75.75 0 0 1-1.5 0v-5a.75.75 0 0 1 .75-.75ZM13 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"],}
}

export default dbInfoCircle;
