// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbInfinity : DbIconDefinition = {
    iconName: "infinity",
    svgPathData: {duotone: ["M2.75 12a4.25 4.25 0 0 0 6.8 3.4.75.75 0 0 1 .9 1.2 5.75 5.75 0 1 1 2.3-4.6 4.25 4.25 0 1 0 1.7-3.4.75.75 0 0 1-.9-1.2 5.75 5.75 0 1 1-2.3 4.6 4.25 4.25 0 0 0-8.5 0Z"],fill: ["M2.75 12a4.25 4.25 0 0 0 6.8 3.4.75.75 0 0 1 .9 1.2 5.75 5.75 0 1 1 2.3-4.6 4.25 4.25 0 1 0 1.7-3.4.75.75 0 0 1-.9-1.2 5.75 5.75 0 1 1-2.3 4.6 4.25 4.25 0 0 0-8.5 0Z"],line: ["M2.75 12a4.25 4.25 0 0 0 6.8 3.4.75.75 0 0 1 .9 1.2 5.75 5.75 0 1 1 2.3-4.6 4.25 4.25 0 1 0 1.7-3.4.75.75 0 0 1-.9-1.2 5.75 5.75 0 1 1-2.3 4.6 4.25 4.25 0 0 0-8.5 0Z"],}
}

export default dbInfinity;
