// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbInfo : DbIconDefinition = {
    iconName: "info",
    svgPathData: {duotone: ["M12.75 21a.75.75 0 0 1-1.5 0V10a.75.75 0 0 1 1.5 0ZM12 4a1 1 0 1 1 0 2 1 1 0 0 1 0-2Z"],fill: ["M12.75 21a.75.75 0 0 1-1.5 0V10a.75.75 0 0 1 1.5 0ZM12 4a1 1 0 1 1 0 2 1 1 0 0 1 0-2Z"],line: ["M12.75 21a.75.75 0 0 1-1.5 0V10a.75.75 0 0 1 1.5 0ZM12 4a1 1 0 1 1 0 2 1 1 0 0 1 0-2Z"],}
}

export default dbInfo;
