// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbInfinitySmall : DbIconDefinition = {
    iconName: "infinitySmall",
    svgPathData: {duotone: ["M6.75 12a2.25 2.25 0 0 0 3.374 1.948.75.75 0 1 1 .752 1.299A3.75 3.75 0 1 1 12.75 12a2.25 2.25 0 1 0 1.126-1.949.75.75 0 1 1-.752-1.299A3.75 3.75 0 1 1 11.25 12a2.25 2.25 0 1 0-4.5 0Z"],fill: ["M6.75 12a2.25 2.25 0 0 0 3.374 1.948.75.75 0 1 1 .752 1.299A3.75 3.75 0 1 1 12.75 12a2.25 2.25 0 1 0 1.126-1.949.75.75 0 1 1-.752-1.299A3.75 3.75 0 1 1 11.25 12a2.25 2.25 0 1 0-4.5 0Z"],line: ["M6.75 12a2.25 2.25 0 0 0 3.374 1.948.75.75 0 1 1 .752 1.299A3.75 3.75 0 1 1 12.75 12a2.25 2.25 0 1 0 1.126-1.949.75.75 0 1 1-.752-1.299A3.75 3.75 0 1 1 11.25 12a2.25 2.25 0 1 0-4.5 0Z"],}
}

export default dbInfinitySmall;
