// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbListBullets : DbIconDefinition = {
    iconName: "listBullets",
    svgPathData: {duotone: ["M20.75 6a.75.75 0 0 1-.75.75H8a.75.75 0 0 1 0-1.5h12a.75.75 0 0 1 .75.75ZM20 11.25a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Zm0 6a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5ZM5 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 7a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm0 12a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],fill: ["M20.75 6a.75.75 0 0 1-.75.75H8a.75.75 0 0 1 0-1.5h12a.75.75 0 0 1 .75.75ZM20 11.25a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Zm0 6a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5ZM5 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 7a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm0 12a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],line: ["M20.75 6a.75.75 0 0 1-.75.75H8a.75.75 0 0 1 0-1.5h12a.75.75 0 0 1 .75.75ZM20 11.25a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Zm0 6a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5ZM5 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 7a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm0 12a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"],}
}

export default dbListBullets;
