// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbLinkSimpleHorizontal : DbIconDefinition = {
    iconName: "linkSimpleHorizontal",
    svgPathData: {duotone: ["M17 7H7a5 5 0 0 0 0 10h10a5 5 0 0 0 0-10Z","M15 6.25h2a5.75 5.75 0 1 1 0 11.5h-2a.75.75 0 0 1 0-1.5h2a4.25 4.25 0 0 0 0-8.5h-2a.75.75 0 0 1 0-1.5ZM2.75 12A4.25 4.25 0 0 0 7 16.25h2a.75.75 0 0 1 0 1.5H7a5.75 5.75 0 1 1 0-11.5h2a.75.75 0 0 1 0 1.5H7A4.25 4.25 0 0 0 2.75 12ZM8 11.25h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],fill: ["M15 6.25h2a5.75 5.75 0 1 1 0 11.5h-2a.75.75 0 0 1 0-1.5h2a4.25 4.25 0 0 0 0-8.5h-2a.75.75 0 0 1 0-1.5ZM2.75 12A4.25 4.25 0 0 0 7 16.25h2a.75.75 0 0 1 0 1.5H7a5.75 5.75 0 1 1 0-11.5h2a.75.75 0 0 1 0 1.5H7A4.25 4.25 0 0 0 2.75 12ZM8 11.25h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],line: ["M15 6.25h2a5.75 5.75 0 1 1 0 11.5h-2a.75.75 0 0 1 0-1.5h2a4.25 4.25 0 0 0 0-8.5h-2a.75.75 0 0 1 0-1.5ZM2.75 12A4.25 4.25 0 0 0 7 16.25h2a.75.75 0 0 1 0 1.5H7a5.75 5.75 0 1 1 0-11.5h2a.75.75 0 0 1 0 1.5H7A4.25 4.25 0 0 0 2.75 12ZM8 11.25h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],}
}

export default dbLinkSimpleHorizontal;
