// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbLinkSimple : DbIconDefinition = {
    iconName: "linkSimple",
    svgPathData: {duotone: ["M7 7v10a5 5 0 0 0 10 0V7A5 5 0 0 0 7 7Z","M12 21.25A4.25 4.25 0 0 0 16.25 17v-2a.75.75 0 0 1 1.5 0v2a5.75 5.75 0 1 1-11.5 0v-2a.75.75 0 0 1 1.5 0v2A4.25 4.25 0 0 0 12 21.25ZM6.25 9V7a5.75 5.75 0 1 1 11.5 0v2a.75.75 0 0 1-1.5 0V7a4.25 4.25 0 0 0-8.5 0v2a.75.75 0 0 1-1.5 0Zm5 7V8a.75.75 0 0 1 1.5 0v8a.75.75 0 0 1-1.5 0Z"],fill: ["M12 21.25A4.25 4.25 0 0 0 16.25 17v-2a.75.75 0 0 1 1.5 0v2a5.75 5.75 0 1 1-11.5 0v-2a.75.75 0 0 1 1.5 0v2A4.25 4.25 0 0 0 12 21.25ZM6.25 9V7a5.75 5.75 0 1 1 11.5 0v2a.75.75 0 0 1-1.5 0V7a4.25 4.25 0 0 0-8.5 0v2a.75.75 0 0 1-1.5 0Zm5 7V8a.75.75 0 0 1 1.5 0v8a.75.75 0 0 1-1.5 0Z"],line: ["M12 21.25A4.25 4.25 0 0 0 16.25 17v-2a.75.75 0 0 1 1.5 0v2a5.75 5.75 0 1 1-11.5 0v-2a.75.75 0 0 1 1.5 0v2A4.25 4.25 0 0 0 12 21.25ZM6.25 9V7a5.75 5.75 0 1 1 11.5 0v2a.75.75 0 0 1-1.5 0V7a4.25 4.25 0 0 0-8.5 0v2a.75.75 0 0 1-1.5 0Zm5 7V8a.75.75 0 0 1 1.5 0v8a.75.75 0 0 1-1.5 0Z"],}
}

export default dbLinkSimple;
