// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbLinkHorizontal : DbIconDefinition = {
    iconName: "linkHorizontal",
    svgPathData: {duotone: ["M6 8h4a3.98 3.98 0 0 1 2 .535A3.983 3.983 0 0 1 14 8h4a4 4 0 0 1 0 8h-4a3.983 3.983 0 0 1-2-.535A3.983 3.983 0 0 1 10 16H6a4 4 0 0 1 0-8Z","M10 7.25A4.75 4.75 0 0 1 14.75 12a.75.75 0 0 1-1.5 0A3.25 3.25 0 0 0 10 8.75H6a3.25 3.25 0 1 0 0 6.5h3a.75.75 0 0 1 0 1.5H6a4.75 4.75 0 0 1 0-9.5Zm8 0a4.75 4.75 0 0 1 0 9.5h-4A4.75 4.75 0 0 1 9.25 12a.75.75 0 0 1 1.5 0A3.25 3.25 0 0 0 14 15.25h4a3.25 3.25 0 1 0 0-6.5h-3a.75.75 0 0 1 0-1.5Z"],fill: ["M10 7.25A4.75 4.75 0 0 1 14.75 12a.75.75 0 0 1-1.5 0A3.25 3.25 0 0 0 10 8.75H6a3.25 3.25 0 1 0 0 6.5h3a.75.75 0 0 1 0 1.5H6a4.75 4.75 0 0 1 0-9.5Zm8 0a4.75 4.75 0 0 1 0 9.5h-4A4.75 4.75 0 0 1 9.25 12a.75.75 0 0 1 1.5 0A3.25 3.25 0 0 0 14 15.25h4a3.25 3.25 0 1 0 0-6.5h-3a.75.75 0 0 1 0-1.5Z"],line: ["M10 7.25A4.75 4.75 0 0 1 14.75 12a.75.75 0 0 1-1.5 0A3.25 3.25 0 0 0 10 8.75H6a3.25 3.25 0 1 0 0 6.5h3a.75.75 0 0 1 0 1.5H6a4.75 4.75 0 0 1 0-9.5Zm8 0a4.75 4.75 0 0 1 0 9.5h-4A4.75 4.75 0 0 1 9.25 12a.75.75 0 0 1 1.5 0A3.25 3.25 0 0 0 14 15.25h4a3.25 3.25 0 1 0 0-6.5h-3a.75.75 0 0 1 0-1.5Z"],}
}

export default dbLinkHorizontal;
