// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbMagnifyingGlassMinus : DbIconDefinition = {
    iconName: "magnifyingGlassMinus",
    svgPathData: {duotone: ["M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z","M2.25 11a8.75 8.75 0 1 1 15.445 5.634l2.835 2.836a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.836-2.835A8.75 8.75 0 0 1 2.25 11ZM11 3.75a7.25 7.25 0 1 0 0 14.5 7.25 7.25 0 0 0 0-14.5Zm-3 6.5h6a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],fill: ["M2.25 11a8.75 8.75 0 1 1 15.445 5.634l2.835 2.836a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.836-2.835A8.75 8.75 0 0 1 2.25 11Zm5 0c0 .414.336.75.75.75h6a.75.75 0 0 0 0-1.5H8a.75.75 0 0 0-.75.75Z"],line: ["M2.25 11a8.75 8.75 0 1 1 15.445 5.634l2.835 2.836a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.836-2.835A8.75 8.75 0 0 1 2.25 11ZM11 3.75a7.25 7.25 0 1 0 0 14.5 7.25 7.25 0 0 0 0-14.5Zm-3 6.5h6a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],}
}

export default dbMagnifyingGlassMinus;
