// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbMartiniGlass : DbIconDefinition = {
    iconName: "martiniGlass",
    svgPathData: {duotone: ["M16.5 9h-9l4.5 6 4.5-6Z","M3 2.25h18a.75.75 0 0 1 .6 1.2l-4.499 5.998-.001.002-4.35 5.8v5H16a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5h3.25v-5L6.901 9.452 6.9 9.45l-4.5-6a.75.75 0 0 1 .6-1.2Zm13.125 6 3.375-4.5h-15l3.375 4.5ZM15 9.75H9l3 4Z"],fill: ["M3 2.25h18a.75.75 0 0 1 .6 1.2l-4.499 5.998-.001.002-4.35 5.8v5H16a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5h3.25v-5L6.901 9.452 6.9 9.45l-4.5-6a.75.75 0 0 1 .6-1.2Zm13.125 6 3.375-4.5h-15l3.375 4.5Z"],line: ["M3 2.25h18a.75.75 0 0 1 .6 1.2l-4.499 5.998-.001.002-4.35 5.8v5H16a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5h3.25v-5L6.901 9.452 6.9 9.45l-4.5-6a.75.75 0 0 1 .6-1.2Zm13.125 6 3.375-4.5h-15l3.375 4.5ZM15 9.75H9l3 4Z"],}
}

export default dbMartiniGlass;
