// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbMagnifyingGlass : DbIconDefinition = {
    iconName: "magnifyingGlass",
    svgPathData: {duotone: ["M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z","M11 2.25a8.75 8.75 0 0 1 6.695 14.384l2.835 2.836a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.836-2.835A8.75 8.75 0 1 1 11 2.25ZM3.75 11a7.25 7.25 0 1 0 14.5 0 7.25 7.25 0 0 0-14.5 0Z"],fill: ["M2.25 11a8.75 8.75 0 1 1 15.445 5.634l2.835 2.836a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.836-2.835A8.75 8.75 0 0 1 2.25 11Z"],line: ["M11 2.25a8.75 8.75 0 0 1 6.695 14.384l2.835 2.836a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-2.836-2.835A8.75 8.75 0 1 1 11 2.25ZM3.75 11a7.25 7.25 0 1 0 14.5 0 7.25 7.25 0 0 0-14.5 0Z"],}
}

export default dbMagnifyingGlass;
