// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbMenuBurgerStairs : DbIconDefinition = {
    iconName: "menuBurgerStairs",
    svgPathData: {duotone: ["M20.75 19a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Zm-5-7a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h11a.75.75 0 0 1 .75.75ZM10 4.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],fill: ["M20.75 19a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Zm-5-7a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h11a.75.75 0 0 1 .75.75ZM10 4.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],line: ["M20.75 19a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Zm-5-7a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h11a.75.75 0 0 1 .75.75ZM10 4.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Z"],}
}

export default dbMenuBurgerStairs;
