// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbMinusSmall : DbIconDefinition = {
    iconName: "minusSmall",
    svgPathData: {duotone: ["M6.25,12 C6.25,11.586 6.586,11.25 7,11.25 L17,11.25 C17.414,11.25 17.75,11.586 17.75,12 C17.75,12.414 17.414,12.75 17,12.75 L7,12.75 C6.586,12.75 6.25,12.414 6.25,12 Z"],fill: ["M6.25,12 C6.25,11.586 6.586,11.25 7,11.25 L17,11.25 C17.414,11.25 17.75,11.586 17.75,12 C17.75,12.414 17.414,12.75 17,12.75 L7,12.75 C6.586,12.75 6.25,12.414 6.25,12 Z"],line: ["M6.25,12 C6.25,11.586 6.586,11.25 7,11.25 L17,11.25 C17.414,11.25 17.75,11.586 17.75,12 C17.75,12.414 17.414,12.75 17,12.75 L7,12.75 C6.586,12.75 6.25,12.414 6.25,12 Z"],}
}

export default dbMinusSmall;
