// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbPauseCircle : DbIconDefinition = {
    iconName: "pauseCircle",
    svgPathData: {duotone: ["M22 12a10 10 0 1 1-20 0 10 10 0 1 1 20 0Z","M12 1.25c5.937 0 10.75 4.813 10.75 10.75S17.937 22.75 12 22.75 1.25 17.937 1.25 12 6.063 1.25 12 1.25ZM2.75 12A9.25 9.25 0 0 0 12 21.25 9.25 9.25 0 0 0 21.25 12 9.25 9.25 0 0 0 12 2.75 9.25 9.25 0 0 0 2.75 12Zm8-3v6a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 1.5 0Zm4 0v6a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 1.5 0Z"],fill: ["M12 1.25c5.937 0 10.75 4.813 10.75 10.75S17.937 22.75 12 22.75 1.25 17.937 1.25 12 6.063 1.25 12 1.25Zm-2 7a.75.75 0 0 0-.75.75v6a.75.75 0 0 0 1.5 0V9a.75.75 0 0 0-.75-.75Zm4 0a.75.75 0 0 0-.75.75v6a.75.75 0 0 0 1.5 0V9a.75.75 0 0 0-.75-.75Z"],line: ["M12 1.25c5.937 0 10.75 4.813 10.75 10.75S17.937 22.75 12 22.75 1.25 17.937 1.25 12 6.063 1.25 12 1.25ZM2.75 12A9.25 9.25 0 0 0 12 21.25 9.25 9.25 0 0 0 21.25 12 9.25 9.25 0 0 0 12 2.75 9.25 9.25 0 0 0 2.75 12Zm8-3v6a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 1.5 0Zm4 0v6a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 1.5 0Z"],}
}

export default dbPauseCircle;
