// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbPinMapRound : DbIconDefinition = {
    iconName: "pinMapRound",
    svgPathData: {duotone: ["M17 7A5 5 0 1 1 7 7a5 5 0 1 1 10 0Z","M11.25 12.701a5.752 5.752 0 1 1 1.5 0V21a.75.75 0 0 1-1.5 0ZM7.75 7a4.25 4.25 0 0 0 4.248 4.25h.005A4.25 4.25 0 1 0 7.75 7Z"],fill: ["M6.25 7a5.752 5.752 0 1 1 6.5 5.701V21a.75.75 0 0 1-1.5 0v-8.299A5.75 5.75 0 0 1 6.25 7Z"],line: ["M11.25 12.701a5.752 5.752 0 1 1 1.5 0V21a.75.75 0 0 1-1.5 0ZM7.75 7a4.25 4.25 0 0 0 4.248 4.25h.005A4.25 4.25 0 1 0 7.75 7Z"],}
}

export default dbPinMapRound;
