// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbPowerOff : DbIconDefinition = {
    iconName: "powerOff",
    svgPathData: {duotone: ["M6.5 5.85a8.25 8.25 0 1 0 11 0 .75.75 0 0 1 1-1.117A9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 5.5 4.733a.751.751 0 0 1 1 1.117ZM12.75 2v10a.75.75 0 0 1-1.5 0V2a.75.75 0 0 1 1.5 0Z"],fill: ["M6.5 5.85a8.25 8.25 0 1 0 11 0 .75.75 0 0 1 1-1.117A9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 5.5 4.733a.751.751 0 0 1 1 1.117ZM12.75 2v10a.75.75 0 0 1-1.5 0V2a.75.75 0 0 1 1.5 0Z"],line: ["M6.5 5.85a8.25 8.25 0 1 0 11 0 .75.75 0 0 1 1-1.117A9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 5.5 4.733a.751.751 0 0 1 1 1.117ZM12.75 2v10a.75.75 0 0 1-1.5 0V2a.75.75 0 0 1 1.5 0Z"],}
}

export default dbPowerOff;
