// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbPowerOffSmall : DbIconDefinition = {
    iconName: "powerOffSmall",
    svgPathData: {duotone: ["M8.062 8.528h.001a5.25 5.25 0 1 0 7.875 0 .75.75 0 1 1 1.125-.993 6.75 6.75 0 1 1-10.125 0 .75.75 0 0 1 1.124.993ZM12.75 6v6a.75.75 0 0 1-1.5 0V6a.75.75 0 0 1 1.5 0Z"],fill: ["M8.062 8.528h.001a5.25 5.25 0 1 0 7.875 0 .75.75 0 1 1 1.125-.993 6.75 6.75 0 1 1-10.125 0 .75.75 0 0 1 1.124.993ZM12.75 6v6a.75.75 0 0 1-1.5 0V6a.75.75 0 0 1 1.5 0Z"],line: ["M8.062 8.528h.001a5.25 5.25 0 1 0 7.875 0 .75.75 0 1 1 1.125-.993 6.75 6.75 0 1 1-10.125 0 .75.75 0 0 1 1.124.993ZM12.75 6v6a.75.75 0 0 1-1.5 0V6a.75.75 0 0 1 1.5 0Z"],}
}

export default dbPowerOffSmall;
