// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbRecord : DbIconDefinition = {
    iconName: "record",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M2.25 12A9.75 9.75 0 0 1 12 2.25 9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12ZM12 3.75a8.25 8.25 0 1 0 0 16.5 8.25 8.25 0 0 0 0-16.5Z"],fill: ["M12 2.25A9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12 9.75 9.75 0 0 1 12 2.25Z"],line: ["M2.25 12A9.75 9.75 0 0 1 12 2.25 9.75 9.75 0 0 1 21.75 12 9.75 9.75 0 0 1 12 21.75 9.75 9.75 0 0 1 2.25 12ZM12 3.75a8.25 8.25 0 1 0 0 16.5 8.25 8.25 0 0 0 0-16.5Z"],}
}

export default dbRecord;
