// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbReplay : DbIconDefinition = {
    iconName: "replay",
    svgPathData: {duotone: ["M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0Z","M5.254 7.25H7.5a.75.75 0 0 1 0 1.5h-4A.75.75 0 0 1 2.75 8V4a.75.75 0 0 1 1.5 0v2.084A9.75 9.75 0 0 1 21.75 12a9.75 9.75 0 0 1-18.486 4.334.75.75 0 0 1 1.344-.668 8.25 8.25 0 1 0 .646-8.416Z"],fill: ["M5.254 7.25H7.5a.75.75 0 0 1 0 1.5h-4A.75.75 0 0 1 2.75 8V4a.75.75 0 0 1 1.5 0v2.084A9.75 9.75 0 0 1 21.75 12a9.75 9.75 0 0 1-18.486 4.334.75.75 0 0 1 1.344-.668 8.25 8.25 0 1 0 .646-8.416Z"],line: ["M5.254 7.25H7.5a.75.75 0 0 1 0 1.5h-4A.75.75 0 0 1 2.75 8V4a.75.75 0 0 1 1.5 0v2.084A9.75 9.75 0 0 1 21.75 12a9.75 9.75 0 0 1-18.486 4.334.75.75 0 0 1 1.344-.668 8.25 8.25 0 1 0 .646-8.416Z"],}
}

export default dbReplay;
