// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbSigma : DbIconDefinition = {
    iconName: "sigma",
    svgPathData: {duotone: ["M5.307 3.713A.75.75 0 0 1 6 3.25h12a.75.75 0 0 1 0 1.5H7.81l6.72 6.72a.75.75 0 0 1 0 1.06l-6.72 6.72H18a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.53-1.28L12.94 12 5.47 4.53a.75.75 0 0 1-.163-.817Z"],fill: ["M5.307 3.713A.75.75 0 0 1 6 3.25h12a.75.75 0 0 1 0 1.5H7.81l6.72 6.72a.75.75 0 0 1 0 1.06l-6.72 6.72H18a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.53-1.28L12.94 12 5.47 4.53a.75.75 0 0 1-.163-.817Z"],line: ["M5.307 3.713A.75.75 0 0 1 6 3.25h12a.75.75 0 0 1 0 1.5H7.81l6.72 6.72a.75.75 0 0 1 0 1.06l-6.72 6.72H18a.75.75 0 0 1 0 1.5H6a.75.75 0 0 1-.53-1.28L12.94 12 5.47 4.53a.75.75 0 0 1-.163-.817Z"],}
}

export default dbSigma;
