// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextAlignLeft : DbIconDefinition = {
    iconName: "textAlignLeft",
    svgPathData: {duotone: ["M4 8.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0-15h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM3.25 14a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Z"],fill: ["M4 8.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0-15h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM3.25 14a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Z"],line: ["M4 8.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0-15h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM3.25 14a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Z"],}
}

export default dbTextAlignLeft;
