// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextAlignJustifySmall : DbIconDefinition = {
    iconName: "textAlignJustifySmall",
    svgPathData: {duotone: ["M20 3.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm.75 8.75a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Zm0 7a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Z"],fill: ["M20 3.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm.75 8.75a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Zm0 7a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Z"],line: ["M20 3.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm.75 8.75a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Zm0 7a.75.75 0 0 1-.75.75H4a.75.75 0 0 1 0-1.5h16a.75.75 0 0 1 .75.75Z"],}
}

export default dbTextAlignJustifySmall;
