// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextAlignCenter : DbIconDefinition = {
    iconName: "textAlignCenter",
    svgPathData: {duotone: ["M4 8.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM7.25 4A.75.75 0 0 1 8 3.25h8a.75.75 0 0 1 0 1.5H8A.75.75 0 0 1 7.25 4ZM8 13.25h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],fill: ["M4 8.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM7.25 4A.75.75 0 0 1 8 3.25h8a.75.75 0 0 1 0 1.5H8A.75.75 0 0 1 7.25 4ZM8 13.25h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],line: ["M4 8.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM7.25 4A.75.75 0 0 1 8 3.25h8a.75.75 0 0 1 0 1.5H8A.75.75 0 0 1 7.25 4ZM8 13.25h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1 0-1.5Z"],}
}

export default dbTextAlignCenter;
