// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbText : DbIconDefinition = {
    iconName: "text",
    svgPathData: {duotone: ["M4.25 4A.75.75 0 0 1 5 3.25h14a.75.75 0 0 1 0 1.5h-6.25V20a.75.75 0 0 1-1.5 0V4.75H5A.75.75 0 0 1 4.25 4Z"],fill: ["M4.25 4A.75.75 0 0 1 5 3.25h14a.75.75 0 0 1 0 1.5h-6.25V20a.75.75 0 0 1-1.5 0V4.75H5A.75.75 0 0 1 4.25 4Z"],line: ["M4.25 4A.75.75 0 0 1 5 3.25h14a.75.75 0 0 1 0 1.5h-6.25V20a.75.75 0 0 1-1.5 0V4.75H5A.75.75 0 0 1 4.25 4Z"],}
}

export default dbText;
