// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextSize : DbIconDefinition = {
    iconName: "textSize",
    svgPathData: {duotone: ["M2 3.25h14a.75.75 0 0 1 0 1.5H9.75V20a.75.75 0 0 1-1.5 0V4.75H2a.75.75 0 0 1 0-1.5Zm12 8h8a.75.75 0 0 1 0 1.5h-3.25V20a.75.75 0 0 1-1.5 0v-7.25H14a.75.75 0 0 1 0-1.5Z"],fill: ["M2 3.25h14a.75.75 0 0 1 0 1.5H9.75V20a.75.75 0 0 1-1.5 0V4.75H2a.75.75 0 0 1 0-1.5Zm12 8h8a.75.75 0 0 1 0 1.5h-3.25V20a.75.75 0 0 1-1.5 0v-7.25H14a.75.75 0 0 1 0-1.5Z"],line: ["M2 3.25h14a.75.75 0 0 1 0 1.5H9.75V20a.75.75 0 0 1-1.5 0V4.75H2a.75.75 0 0 1 0-1.5Zm12 8h8a.75.75 0 0 1 0 1.5h-3.25V20a.75.75 0 0 1-1.5 0v-7.25H14a.75.75 0 0 1 0-1.5Z"],}
}

export default dbTextSize;
