// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTemperatureEmpty : DbIconDefinition = {
    iconName: "temperatureEmpty",
    svgPathData: {duotone: ["M12 22a5 5 0 0 0 3-9V5a3 3 0 1 0-6 0v8a5 5 0 0 0 3 9Z","M12 1.25A3.75 3.75 0 0 1 15.75 5v7.641a5.75 5.75 0 1 1-7.5 0V5A3.75 3.75 0 0 1 12 1.25ZM9.75 5v8a.75.75 0 0 1-.3.6 4.251 4.251 0 1 0 6.582 4.744A4.252 4.252 0 0 0 14.55 13.6a.75.75 0 0 1-.3-.6V5a2.25 2.25 0 1 0-4.5 0ZM12 19a2 2 0 1 1-.001-3.999A2 2 0 0 1 12 19Z"],fill: ["M12 1.25A3.75 3.75 0 0 1 15.75 5v7.641a5.75 5.75 0 1 1-7.5 0V5A3.75 3.75 0 0 1 12 1.25ZM14 17a2 2 0 1 0-3.999-.001A2 2 0 0 0 14 17Z"],line: ["M12 1.25A3.75 3.75 0 0 1 15.75 5v7.641a5.75 5.75 0 1 1-7.5 0V5A3.75 3.75 0 0 1 12 1.25ZM9.75 5v8a.75.75 0 0 1-.3.6 4.251 4.251 0 1 0 6.582 4.744A4.252 4.252 0 0 0 14.55 13.6a.75.75 0 0 1-.3-.6V5a2.25 2.25 0 1 0-4.5 0ZM12 19a2 2 0 1 1-.001-3.999A2 2 0 0 1 12 19Z"],}
}

export default dbTemperatureEmpty;
