// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTemperatureHalf : DbIconDefinition = {
    iconName: "temperatureHalf",
    svgPathData: {duotone: ["M12 22a5 5 0 0 0 3-9V5a3 3 0 1 0-6 0v8a5 5 0 0 0 3 9Z","M8.25 5a3.75 3.75 0 0 1 7.5 0v7.641a5.75 5.75 0 1 1-7.5 0ZM12 2.75A2.25 2.25 0 0 0 9.75 5v8a.75.75 0 0 1-.3.6 4.251 4.251 0 1 0 6.582 4.744A4.252 4.252 0 0 0 14.55 13.6a.75.75 0 0 1-.3-.6V5A2.25 2.25 0 0 0 12 2.75ZM14 17a2 2 0 1 1-2.75-1.854V10a.75.75 0 0 1 1.5 0v5.146A2.001 2.001 0 0 1 14 17Z"],fill: ["M12 1.25A3.75 3.75 0 0 1 15.75 5v7.641a5.75 5.75 0 1 1-7.5 0V5A3.75 3.75 0 0 1 12 1.25ZM12 19a2 2 0 0 0 .75-3.855V10a.75.75 0 0 0-1.5 0v5.145A2 2 0 0 0 12 19Z"],line: ["M8.25 5a3.75 3.75 0 0 1 7.5 0v7.641a5.75 5.75 0 1 1-7.5 0ZM12 2.75A2.25 2.25 0 0 0 9.75 5v8a.75.75 0 0 1-.3.6 4.251 4.251 0 1 0 6.582 4.744A4.252 4.252 0 0 0 14.55 13.6a.75.75 0 0 1-.3-.6V5A2.25 2.25 0 0 0 12 2.75ZM14 17a2 2 0 1 1-2.75-1.854V10a.75.75 0 0 1 1.5 0v5.146A2.001 2.001 0 0 1 14 17Z"],}
}

export default dbTemperatureHalf;
