// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextAlignRight : DbIconDefinition = {
    iconName: "textAlignRight",
    svgPathData: {duotone: ["M20 8.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM20.75 4a.75.75 0 0 1-.75.75h-8a.75.75 0 0 1 0-1.5h8a.75.75 0 0 1 .75.75ZM20 13.25a.75.75 0 0 1 0 1.5h-8a.75.75 0 0 1 0-1.5Z"],fill: ["M20 8.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM20.75 4a.75.75 0 0 1-.75.75h-8a.75.75 0 0 1 0-1.5h8a.75.75 0 0 1 .75.75ZM20 13.25a.75.75 0 0 1 0 1.5h-8a.75.75 0 0 1 0-1.5Z"],line: ["M20 8.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5Zm0 10a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM20.75 4a.75.75 0 0 1-.75.75h-8a.75.75 0 0 1 0-1.5h8a.75.75 0 0 1 .75.75ZM20 13.25a.75.75 0 0 1 0 1.5h-8a.75.75 0 0 1 0-1.5Z"],}
}

export default dbTextAlignRight;
