// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextAlignLeftSmall : DbIconDefinition = {
    iconName: "textAlignLeftSmall",
    svgPathData: {duotone: ["M4 4.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM3.25 19a.75.75 0 0 1 .75-.75h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Zm0-7a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Z"],fill: ["M4 4.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM3.25 19a.75.75 0 0 1 .75-.75h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Zm0-7a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Z"],line: ["M4 4.25h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5ZM3.25 19a.75.75 0 0 1 .75-.75h16a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Zm0-7a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1-.75-.75Z"],}
}

export default dbTextAlignLeftSmall;
