// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbTextOff : DbIconDefinition = {
    iconName: "textOff",
    svgPathData: {duotone: ["M1.47 2.53a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l20 20a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-8.72-8.72V20a.75.75 0 0 1-1.5 0v-7.69ZM8 3.25h11a.75.75 0 0 1 0 1.5h-6.25V8a.75.75 0 0 1-1.5 0V4.75H8a.75.75 0 0 1 0-1.5Z"],fill: ["M1.47 2.53a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l20 20a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-8.72-8.72V20a.75.75 0 0 1-1.5 0v-7.69ZM8 3.25h11a.75.75 0 0 1 0 1.5h-6.25V8a.75.75 0 0 1-1.5 0V4.75H8a.75.75 0 0 1 0-1.5Z"],line: ["M1.47 2.53a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018l20 20a.749.749 0 0 1-.326 1.275.749.749 0 0 1-.734-.215l-8.72-8.72V20a.75.75 0 0 1-1.5 0v-7.69ZM8 3.25h11a.75.75 0 0 1 0 1.5h-6.25V8a.75.75 0 0 1-1.5 0V4.75H8a.75.75 0 0 1 0-1.5Z"],}
}

export default dbTextOff;
