// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbToggleOn : DbIconDefinition = {
    iconName: "toggleOn",
    svgPathData: {duotone: ["M19 12a4 4 0 1 1-8 0 4 4 0 1 1 8 0Z","M9 4.25h6a7.75 7.75 0 0 1 0 15.5H9a7.75 7.75 0 0 1 0-15.5ZM2.75 12A6.25 6.25 0 0 0 9 18.25h6a6.25 6.25 0 1 0 0-12.5H9A6.25 6.25 0 0 0 2.75 12ZM15 7.25a4.75 4.75 0 1 1 0 9.5 4.75 4.75 0 0 1 0-9.5ZM11.75 12a3.25 3.25 0 1 0 6.5 0 3.25 3.25 0 0 0-6.5 0Z"],fill: ["M1.25 12A7.75 7.75 0 0 1 9 4.25h6a7.75 7.75 0 0 1 0 15.5H9A7.75 7.75 0 0 1 1.25 12ZM9 5.75a6.25 6.25 0 1 0 0 12.5h6a6.25 6.25 0 1 0 0-12.5ZM10.25 12a4.75 4.75 0 1 1 9.5 0 4.75 4.75 0 0 1-9.5 0Z"],line: ["M9 4.25h6a7.75 7.75 0 0 1 0 15.5H9a7.75 7.75 0 0 1 0-15.5ZM2.75 12A6.25 6.25 0 0 0 9 18.25h6a6.25 6.25 0 1 0 0-12.5H9A6.25 6.25 0 0 0 2.75 12ZM15 7.25a4.75 4.75 0 1 1 0 9.5 4.75 4.75 0 0 1 0-9.5ZM11.75 12a3.25 3.25 0 1 0 6.5 0 3.25 3.25 0 0 0-6.5 0Z"],}
}

export default dbToggleOn;
