// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import { DbIconDefinition } from "@digibearapp/digibear-common-types";

const dbVoicemail : DbIconDefinition = {
    iconName: "voicemail",
    svgPathData: {duotone: ["M6 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8Zm12 0a4 4 0 1 1 0-8 4 4 0 0 1 0 8Z","M9.464 15.25h5.072A4.75 4.75 0 1 1 18 16.75H6a4.75 4.75 0 1 1 3.464-1.5Zm8.536 0a3.25 3.25 0 1 0 0-6.5 3.25 3.25 0 0 0 0 6.5ZM6 8.75a3.25 3.25 0 1 0 0 6.5 3.25 3.25 0 0 0 0-6.5Z"],fill: ["M9.465 15.25h5.07a4.749 4.749 0 1 1 8.115-2.287A4.749 4.749 0 0 1 18 16.75H6a4.749 4.749 0 0 1-4.65-3.787 4.748 4.748 0 0 1 8.536-3.695 4.748 4.748 0 0 1-.421 5.982Zm8.535 0a3.25 3.25 0 1 0 0-6.5 3.25 3.25 0 0 0 0 6.5ZM6 8.75a3.25 3.25 0 1 0 0 6.5 3.25 3.25 0 0 0 0-6.5Z"],line: ["M9.465 15.25h5.07a4.749 4.749 0 1 1 8.115-2.287A4.749 4.749 0 0 1 18 16.75H6a4.749 4.749 0 0 1-4.65-3.787 4.748 4.748 0 0 1 8.536-3.695 4.748 4.748 0 0 1-.421 5.982Zm8.535 0a3.25 3.25 0 1 0 0-6.5 3.25 3.25 0 0 0 0 6.5ZM6 8.75a3.25 3.25 0 1 0 0 6.5 3.25 3.25 0 0 0 0-6.5Z"],}
}

export default dbVoicemail;
